// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseEnvelope.proto

package serenno.protos.responseEnvelope;

public interface DynamicMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.responseEnvelope.DynamicMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int32 message_id = 4;</code>
   * @return The messageId.
   */
  int getMessageId();
}
