// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseEnvelope.proto

package serenno.protos.responseEnvelope;

public interface ResponseEnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.responseEnvelope.ResponseEnvelope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 correlation_id = 1;</code>
   * @return The correlationId.
   */
  int getCorrelationId();

  /**
   * <code>int64 current_server_time = 2;</code>
   * @return The currentServerTime.
   */
  long getCurrentServerTime();

  /**
   * <code>bytes payload = 4;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>.serenno.protos.responseEnvelope.ResponseCode code = 5;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.serenno.protos.responseEnvelope.ResponseCode code = 5;</code>
   * @return The code.
   */
  ResponseCode getCode();

  /**
   * <code>string message = 6;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 6;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.serenno.protos.responseEnvelope.ContentEncoding content_encoding = 7;</code>
   * @return The enum numeric value on the wire for contentEncoding.
   */
  int getContentEncodingValue();
  /**
   * <code>.serenno.protos.responseEnvelope.ContentEncoding content_encoding = 7;</code>
   * @return The contentEncoding.
   */
  ContentEncoding getContentEncoding();

  /**
   * <code>string stack_trace = 8;</code>
   * @return The stackTrace.
   */
  String getStackTrace();
  /**
   * <code>string stack_trace = 8;</code>
   * @return The bytes for stackTrace.
   */
  com.google.protobuf.ByteString
      getStackTraceBytes();

  /**
   * <code>repeated .serenno.protos.responseEnvelope.DynamicMessage dynamic_message = 9;</code>
   */
  java.util.List<DynamicMessage>
      getDynamicMessageList();
  /**
   * <code>repeated .serenno.protos.responseEnvelope.DynamicMessage dynamic_message = 9;</code>
   */
  DynamicMessage getDynamicMessage(int index);
  /**
   * <code>repeated .serenno.protos.responseEnvelope.DynamicMessage dynamic_message = 9;</code>
   */
  int getDynamicMessageCount();
  /**
   * <code>repeated .serenno.protos.responseEnvelope.DynamicMessage dynamic_message = 9;</code>
   */
  java.util.List<? extends DynamicMessageOrBuilder>
      getDynamicMessageOrBuilderList();
  /**
   * <code>repeated .serenno.protos.responseEnvelope.DynamicMessage dynamic_message = 9;</code>
   */
  DynamicMessageOrBuilder getDynamicMessageOrBuilder(
      int index);

  /**
   * <code>string maintenance_message = 10;</code>
   * @return The maintenanceMessage.
   */
  String getMaintenanceMessage();
  /**
   * <code>string maintenance_message = 10;</code>
   * @return The bytes for maintenanceMessage.
   */
  com.google.protobuf.ByteString
      getMaintenanceMessageBytes();

  /**
   * <code>string maintenance_link = 11;</code>
   * @return The maintenanceLink.
   */
  String getMaintenanceLink();
  /**
   * <code>string maintenance_link = 11;</code>
   * @return The bytes for maintenanceLink.
   */
  com.google.protobuf.ByteString
      getMaintenanceLinkBytes();

  /**
   * <code>int32 sub_code = 12;</code>
   * @return The subCode.
   */
  int getSubCode();
}
