// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthGuestResponse.proto

package serenno.protos.authGuestResponse;

public final class AuthGuestResponseOuterClass {
  private AuthGuestResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serenno_authGuestResponse_AuthGuestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serenno_authGuestResponse_AuthGuestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027AuthGuestResponse.proto\022\031serenno.authG" +
      "uestResponse\"8\n\021AuthGuestResponse\022\017\n\007aut" +
      "h_id\030\001 \001(\t\022\022\n\nauth_token\030\002 \001(\tB\002P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_serenno_authGuestResponse_AuthGuestResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serenno_authGuestResponse_AuthGuestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serenno_authGuestResponse_AuthGuestResponse_descriptor,
        new String[] { "AuthId", "AuthToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
