// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

/**
 * Protobuf type {@code serenno.protos.playerProfileResponse.ArenaUnit}
 */
public final class ArenaUnit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serenno.protos.playerProfileResponse.ArenaUnit)
    ArenaUnitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ArenaUnit.newBuilder() to construct.
  private ArenaUnit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ArenaUnit() {
    defId_ = "";
    slotType_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ArenaUnit();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ArenaUnit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            defId_ = s;
            break;
          }
          case 24: {

            index_ = input.readInt32();
            break;
          }
          case 96: {
            int rawValue = input.readEnum();

            slotType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_ArenaUnit_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_ArenaUnit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ArenaUnit.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @Override
  public int getId() {
    return id_;
  }

  public static final int DEFID_FIELD_NUMBER = 2;
  private volatile Object defId_;
  /**
   * <code>string defId = 2;</code>
   * @return The defId.
   */
  @Override
  public String getDefId() {
    Object ref = defId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      defId_ = s;
      return s;
    }
  }
  /**
   * <code>string defId = 2;</code>
   * @return The bytes for defId.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefIdBytes() {
    Object ref = defId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      defId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 3;
  private int index_;
  /**
   * <code>int32 index = 3;</code>
   * @return The index.
   */
  @Override
  public int getIndex() {
    return index_;
  }

  public static final int SLOTTYPE_FIELD_NUMBER = 12;
  private int slotType_;
  /**
   * <pre>
   * int32 unknown1 = 11;
   * </pre>
   *
   * <code>.serenno.protos.playerProfileResponse.SlotType slotType = 12;</code>
   * @return The enum numeric value on the wire for slotType.
   */
  @Override public int getSlotTypeValue() {
    return slotType_;
  }
  /**
   * <pre>
   * int32 unknown1 = 11;
   * </pre>
   *
   * <code>.serenno.protos.playerProfileResponse.SlotType slotType = 12;</code>
   * @return The slotType.
   */
  @Override public SlotType getSlotType() {
    @SuppressWarnings("deprecation")
    SlotType result = SlotType.valueOf(slotType_);
    return result == null ? SlotType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getDefIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, defId_);
    }
    if (index_ != 0) {
      output.writeInt32(3, index_);
    }
    if (slotType_ != SlotType.SlotTypeNONE.getNumber()) {
      output.writeEnum(12, slotType_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getDefIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, defId_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, index_);
    }
    if (slotType_ != SlotType.SlotTypeNONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, slotType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ArenaUnit)) {
      return super.equals(obj);
    }
    ArenaUnit other = (ArenaUnit) obj;

    if (getId()
        != other.getId()) return false;
    if (!getDefId()
        .equals(other.getDefId())) return false;
    if (getIndex()
        != other.getIndex()) return false;
    if (slotType_ != other.slotType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + DEFID_FIELD_NUMBER;
    hash = (53 * hash) + getDefId().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + SLOTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + slotType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ArenaUnit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ArenaUnit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ArenaUnit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ArenaUnit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ArenaUnit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ArenaUnit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ArenaUnit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ArenaUnit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ArenaUnit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ArenaUnit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ArenaUnit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ArenaUnit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ArenaUnit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code serenno.protos.playerProfileResponse.ArenaUnit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serenno.protos.playerProfileResponse.ArenaUnit)
      ArenaUnitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_ArenaUnit_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_ArenaUnit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ArenaUnit.class, Builder.class);
    }

    // Construct using serenno.protos.playerProfileResponse.ArenaUnit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      defId_ = "";

      index_ = 0;

      slotType_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_ArenaUnit_descriptor;
    }

    @Override
    public ArenaUnit getDefaultInstanceForType() {
      return ArenaUnit.getDefaultInstance();
    }

    @Override
    public ArenaUnit build() {
      ArenaUnit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ArenaUnit buildPartial() {
      ArenaUnit result = new ArenaUnit(this);
      result.id_ = id_;
      result.defId_ = defId_;
      result.index_ = index_;
      result.slotType_ = slotType_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ArenaUnit) {
        return mergeFrom((ArenaUnit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ArenaUnit other) {
      if (other == ArenaUnit.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getDefId().isEmpty()) {
        defId_ = other.defId_;
        onChanged();
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (other.slotType_ != 0) {
        setSlotTypeValue(other.getSlotTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ArenaUnit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ArenaUnit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private Object defId_ = "";
    /**
     * <code>string defId = 2;</code>
     * @return The defId.
     */
    public String getDefId() {
      Object ref = defId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        defId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string defId = 2;</code>
     * @return The bytes for defId.
     */
    public com.google.protobuf.ByteString
        getDefIdBytes() {
      Object ref = defId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        defId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string defId = 2;</code>
     * @param value The defId to set.
     * @return This builder for chaining.
     */
    public Builder setDefId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string defId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefId() {
      
      defId_ = getDefaultInstance().getDefId();
      onChanged();
      return this;
    }
    /**
     * <code>string defId = 2;</code>
     * @param value The bytes for defId to set.
     * @return This builder for chaining.
     */
    public Builder setDefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defId_ = value;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    @Override
    public int getIndex() {
      return index_;
    }
    /**
     * <code>int32 index = 3;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private int slotType_ = 0;
    /**
     * <pre>
     * int32 unknown1 = 11;
     * </pre>
     *
     * <code>.serenno.protos.playerProfileResponse.SlotType slotType = 12;</code>
     * @return The enum numeric value on the wire for slotType.
     */
    @Override public int getSlotTypeValue() {
      return slotType_;
    }
    /**
     * <pre>
     * int32 unknown1 = 11;
     * </pre>
     *
     * <code>.serenno.protos.playerProfileResponse.SlotType slotType = 12;</code>
     * @param value The enum numeric value on the wire for slotType to set.
     * @return This builder for chaining.
     */
    public Builder setSlotTypeValue(int value) {
      
      slotType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int32 unknown1 = 11;
     * </pre>
     *
     * <code>.serenno.protos.playerProfileResponse.SlotType slotType = 12;</code>
     * @return The slotType.
     */
    @Override
    public SlotType getSlotType() {
      @SuppressWarnings("deprecation")
      SlotType result = SlotType.valueOf(slotType_);
      return result == null ? SlotType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * int32 unknown1 = 11;
     * </pre>
     *
     * <code>.serenno.protos.playerProfileResponse.SlotType slotType = 12;</code>
     * @param value The slotType to set.
     * @return This builder for chaining.
     */
    public Builder setSlotType(SlotType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      slotType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int32 unknown1 = 11;
     * </pre>
     *
     * <code>.serenno.protos.playerProfileResponse.SlotType slotType = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlotType() {
      
      slotType_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:serenno.protos.playerProfileResponse.ArenaUnit)
  }

  // @@protoc_insertion_point(class_scope:serenno.protos.playerProfileResponse.ArenaUnit)
  private static final ArenaUnit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ArenaUnit();
  }

  public static ArenaUnit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ArenaUnit>
      PARSER = new com.google.protobuf.AbstractParser<ArenaUnit>() {
    @Override
    public ArenaUnit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ArenaUnit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ArenaUnit> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ArenaUnit> getParserForType() {
    return PARSER;
  }

  @Override
  public ArenaUnit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

