// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

public interface ArenaTeamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.playerProfileResponse.ArenaTeam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *int32 unknown1 = 4;
   *int64 unknown2 = 7;
   * </pre>
   *
   * <code>repeated .serenno.protos.playerProfileResponse.ArenaUnit arenaUnit = 1;</code>
   */
  java.util.List<ArenaUnit>
      getArenaUnitList();
  /**
   * <pre>
   *int32 unknown1 = 4;
   *int64 unknown2 = 7;
   * </pre>
   *
   * <code>repeated .serenno.protos.playerProfileResponse.ArenaUnit arenaUnit = 1;</code>
   */
  ArenaUnit getArenaUnit(int index);
  /**
   * <pre>
   *int32 unknown1 = 4;
   *int64 unknown2 = 7;
   * </pre>
   *
   * <code>repeated .serenno.protos.playerProfileResponse.ArenaUnit arenaUnit = 1;</code>
   */
  int getArenaUnitCount();
  /**
   * <pre>
   *int32 unknown1 = 4;
   *int64 unknown2 = 7;
   * </pre>
   *
   * <code>repeated .serenno.protos.playerProfileResponse.ArenaUnit arenaUnit = 1;</code>
   */
  java.util.List<? extends ArenaUnitOrBuilder>
      getArenaUnitOrBuilderList();
  /**
   * <pre>
   *int32 unknown1 = 4;
   *int64 unknown2 = 7;
   * </pre>
   *
   * <code>repeated .serenno.protos.playerProfileResponse.ArenaUnit arenaUnit = 1;</code>
   */
  ArenaUnitOrBuilder getArenaUnitOrBuilder(
      int index);
}
