// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

public interface CurrencyItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.playerProfileResponse.CurrencyItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyType currency = 1;</code>
   * @return The enum numeric value on the wire for currency.
   */
  int getCurrencyValue();
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyType currency = 1;</code>
   * @return The currency.
   */
  CurrencyType getCurrency();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
