// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

/**
 * Protobuf enum {@code serenno.protos.playerProfileResponse.Rarity}
 */
public enum Rarity
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ZERO_STAR = 0;</code>
   */
  ZERO_STAR(0),
  /**
   * <code>ONE_STAR = 1;</code>
   */
  ONE_STAR(1),
  /**
   * <code>TWO_STAR = 2;</code>
   */
  TWO_STAR(2),
  /**
   * <code>THREE_STAR = 3;</code>
   */
  THREE_STAR(3),
  /**
   * <code>FOUR_STAR = 4;</code>
   */
  FOUR_STAR(4),
  /**
   * <code>FIVE_STAR = 5;</code>
   */
  FIVE_STAR(5),
  /**
   * <code>SIX_STAR = 6;</code>
   */
  SIX_STAR(6),
  /**
   * <code>SEVEN_STAR = 7;</code>
   */
  SEVEN_STAR(7),
  /**
   * <code>NO_STAR = 8;</code>
   */
  NO_STAR(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ZERO_STAR = 0;</code>
   */
  public static final int ZERO_STAR_VALUE = 0;
  /**
   * <code>ONE_STAR = 1;</code>
   */
  public static final int ONE_STAR_VALUE = 1;
  /**
   * <code>TWO_STAR = 2;</code>
   */
  public static final int TWO_STAR_VALUE = 2;
  /**
   * <code>THREE_STAR = 3;</code>
   */
  public static final int THREE_STAR_VALUE = 3;
  /**
   * <code>FOUR_STAR = 4;</code>
   */
  public static final int FOUR_STAR_VALUE = 4;
  /**
   * <code>FIVE_STAR = 5;</code>
   */
  public static final int FIVE_STAR_VALUE = 5;
  /**
   * <code>SIX_STAR = 6;</code>
   */
  public static final int SIX_STAR_VALUE = 6;
  /**
   * <code>SEVEN_STAR = 7;</code>
   */
  public static final int SEVEN_STAR_VALUE = 7;
  /**
   * <code>NO_STAR = 8;</code>
   */
  public static final int NO_STAR_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static Rarity valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Rarity forNumber(int value) {
    switch (value) {
      case 0: return ZERO_STAR;
      case 1: return ONE_STAR;
      case 2: return TWO_STAR;
      case 3: return THREE_STAR;
      case 4: return FOUR_STAR;
      case 5: return FIVE_STAR;
      case 6: return SIX_STAR;
      case 7: return SEVEN_STAR;
      case 8: return NO_STAR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Rarity>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Rarity> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Rarity>() {
          public Rarity findValueByNumber(int number) {
            return Rarity.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return PlayerProfileResponseOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final Rarity[] VALUES = values();

  public static Rarity valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Rarity(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:serenno.protos.playerProfileResponse.Rarity)
}

