// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

/**
 * Protobuf type {@code serenno.protos.playerProfileResponse.StatMod}
 */
public final class StatMod extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serenno.protos.playerProfileResponse.StatMod)
    StatModOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatMod.newBuilder() to construct.
  private StatMod(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatMod() {
    id_ = "";
    definitionId_ = "";
    tier_ = 0;
    secondaryStat_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatMod();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StatMod(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            definitionId_ = s;
            break;
          }
          case 32: {

            level_ = input.readInt32();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            tier_ = rawValue;
            break;
          }
          case 74: {
            CurrencyItem.Builder subBuilder = null;
            if (sellValue_ != null) {
              subBuilder = sellValue_.toBuilder();
            }
            sellValue_ = input.readMessage(CurrencyItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sellValue_);
              sellValue_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            CurrencyItem.Builder subBuilder = null;
            if (removeCost_ != null) {
              subBuilder = removeCost_.toBuilder();
            }
            removeCost_ = input.readMessage(CurrencyItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(removeCost_);
              removeCost_ = subBuilder.buildPartial();
            }

            break;
          }
          case 88: {

            locked_ = input.readBool();
            break;
          }
          case 98: {
            StatModStat.Builder subBuilder = null;
            if (primaryStat_ != null) {
              subBuilder = primaryStat_.toBuilder();
            }
            primaryStat_ = input.readMessage(StatModStat.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(primaryStat_);
              primaryStat_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              secondaryStat_ = new java.util.ArrayList<StatModStat>();
              mutable_bitField0_ |= 0x00000001;
            }
            secondaryStat_.add(
                input.readMessage(StatModStat.parser(), extensionRegistry));
            break;
          }
          case 112: {

            xp_ = input.readInt32();
            break;
          }
          case 122: {
            CurrencyItem.Builder subBuilder = null;
            if (levelCost_ != null) {
              subBuilder = levelCost_.toBuilder();
            }
            levelCost_ = input.readMessage(CurrencyItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(levelCost_);
              levelCost_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        secondaryStat_ = java.util.Collections.unmodifiableList(secondaryStat_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_StatMod_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_StatMod_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StatMod.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFINITION_ID_FIELD_NUMBER = 2;
  private volatile Object definitionId_;
  /**
   * <code>string definition_id = 2;</code>
   * @return The definitionId.
   */
  @Override
  public String getDefinitionId() {
    Object ref = definitionId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      definitionId_ = s;
      return s;
    }
  }
  /**
   * <code>string definition_id = 2;</code>
   * @return The bytes for definitionId.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefinitionIdBytes() {
    Object ref = definitionId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      definitionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEVEL_FIELD_NUMBER = 4;
  private int level_;
  /**
   * <code>int32 level = 4;</code>
   * @return The level.
   */
  @Override
  public int getLevel() {
    return level_;
  }

  public static final int TIER_FIELD_NUMBER = 5;
  private int tier_;
  /**
   * <code>.serenno.protos.playerProfileResponse.StatModTier tier = 5;</code>
   * @return The enum numeric value on the wire for tier.
   */
  @Override public int getTierValue() {
    return tier_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.StatModTier tier = 5;</code>
   * @return The tier.
   */
  @Override public StatModTier getTier() {
    @SuppressWarnings("deprecation")
    StatModTier result = StatModTier.valueOf(tier_);
    return result == null ? StatModTier.UNRECOGNIZED : result;
  }

  public static final int SELL_VALUE_FIELD_NUMBER = 9;
  private CurrencyItem sellValue_;
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
   * @return Whether the sellValue field is set.
   */
  @Override
  public boolean hasSellValue() {
    return sellValue_ != null;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
   * @return The sellValue.
   */
  @Override
  public CurrencyItem getSellValue() {
    return sellValue_ == null ? CurrencyItem.getDefaultInstance() : sellValue_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
   */
  @Override
  public CurrencyItemOrBuilder getSellValueOrBuilder() {
    return getSellValue();
  }

  public static final int REMOVE_COST_FIELD_NUMBER = 10;
  private CurrencyItem removeCost_;
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
   * @return Whether the removeCost field is set.
   */
  @Override
  public boolean hasRemoveCost() {
    return removeCost_ != null;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
   * @return The removeCost.
   */
  @Override
  public CurrencyItem getRemoveCost() {
    return removeCost_ == null ? CurrencyItem.getDefaultInstance() : removeCost_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
   */
  @Override
  public CurrencyItemOrBuilder getRemoveCostOrBuilder() {
    return getRemoveCost();
  }

  public static final int LOCKED_FIELD_NUMBER = 11;
  private boolean locked_;
  /**
   * <code>bool locked = 11;</code>
   * @return The locked.
   */
  @Override
  public boolean getLocked() {
    return locked_;
  }

  public static final int PRIMARY_STAT_FIELD_NUMBER = 12;
  private StatModStat primaryStat_;
  /**
   * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
   * @return Whether the primaryStat field is set.
   */
  @Override
  public boolean hasPrimaryStat() {
    return primaryStat_ != null;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
   * @return The primaryStat.
   */
  @Override
  public StatModStat getPrimaryStat() {
    return primaryStat_ == null ? StatModStat.getDefaultInstance() : primaryStat_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
   */
  @Override
  public StatModStatOrBuilder getPrimaryStatOrBuilder() {
    return getPrimaryStat();
  }

  public static final int SECONDARY_STAT_FIELD_NUMBER = 13;
  private java.util.List<StatModStat> secondaryStat_;
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
   */
  @Override
  public java.util.List<StatModStat> getSecondaryStatList() {
    return secondaryStat_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
   */
  @Override
  public java.util.List<? extends StatModStatOrBuilder>
      getSecondaryStatOrBuilderList() {
    return secondaryStat_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
   */
  @Override
  public int getSecondaryStatCount() {
    return secondaryStat_.size();
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
   */
  @Override
  public StatModStat getSecondaryStat(int index) {
    return secondaryStat_.get(index);
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
   */
  @Override
  public StatModStatOrBuilder getSecondaryStatOrBuilder(
      int index) {
    return secondaryStat_.get(index);
  }

  public static final int XP_FIELD_NUMBER = 14;
  private int xp_;
  /**
   * <code>int32 xp = 14;</code>
   * @return The xp.
   */
  @Override
  public int getXp() {
    return xp_;
  }

  public static final int LEVEL_COST_FIELD_NUMBER = 15;
  private CurrencyItem levelCost_;
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
   * @return Whether the levelCost field is set.
   */
  @Override
  public boolean hasLevelCost() {
    return levelCost_ != null;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
   * @return The levelCost.
   */
  @Override
  public CurrencyItem getLevelCost() {
    return levelCost_ == null ? CurrencyItem.getDefaultInstance() : levelCost_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
   */
  @Override
  public CurrencyItemOrBuilder getLevelCostOrBuilder() {
    return getLevelCost();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getDefinitionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, definitionId_);
    }
    if (level_ != 0) {
      output.writeInt32(4, level_);
    }
    if (tier_ != StatModTier.STATMOD_TIER_00.getNumber()) {
      output.writeEnum(5, tier_);
    }
    if (sellValue_ != null) {
      output.writeMessage(9, getSellValue());
    }
    if (removeCost_ != null) {
      output.writeMessage(10, getRemoveCost());
    }
    if (locked_ != false) {
      output.writeBool(11, locked_);
    }
    if (primaryStat_ != null) {
      output.writeMessage(12, getPrimaryStat());
    }
    for (int i = 0; i < secondaryStat_.size(); i++) {
      output.writeMessage(13, secondaryStat_.get(i));
    }
    if (xp_ != 0) {
      output.writeInt32(14, xp_);
    }
    if (levelCost_ != null) {
      output.writeMessage(15, getLevelCost());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getDefinitionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, definitionId_);
    }
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, level_);
    }
    if (tier_ != StatModTier.STATMOD_TIER_00.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, tier_);
    }
    if (sellValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getSellValue());
    }
    if (removeCost_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getRemoveCost());
    }
    if (locked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, locked_);
    }
    if (primaryStat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getPrimaryStat());
    }
    for (int i = 0; i < secondaryStat_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, secondaryStat_.get(i));
    }
    if (xp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, xp_);
    }
    if (levelCost_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getLevelCost());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StatMod)) {
      return super.equals(obj);
    }
    StatMod other = (StatMod) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getDefinitionId()
        .equals(other.getDefinitionId())) return false;
    if (getLevel()
        != other.getLevel()) return false;
    if (tier_ != other.tier_) return false;
    if (hasSellValue() != other.hasSellValue()) return false;
    if (hasSellValue()) {
      if (!getSellValue()
          .equals(other.getSellValue())) return false;
    }
    if (hasRemoveCost() != other.hasRemoveCost()) return false;
    if (hasRemoveCost()) {
      if (!getRemoveCost()
          .equals(other.getRemoveCost())) return false;
    }
    if (getLocked()
        != other.getLocked()) return false;
    if (hasPrimaryStat() != other.hasPrimaryStat()) return false;
    if (hasPrimaryStat()) {
      if (!getPrimaryStat()
          .equals(other.getPrimaryStat())) return false;
    }
    if (!getSecondaryStatList()
        .equals(other.getSecondaryStatList())) return false;
    if (getXp()
        != other.getXp()) return false;
    if (hasLevelCost() != other.hasLevelCost()) return false;
    if (hasLevelCost()) {
      if (!getLevelCost()
          .equals(other.getLevelCost())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DEFINITION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDefinitionId().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + TIER_FIELD_NUMBER;
    hash = (53 * hash) + tier_;
    if (hasSellValue()) {
      hash = (37 * hash) + SELL_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getSellValue().hashCode();
    }
    if (hasRemoveCost()) {
      hash = (37 * hash) + REMOVE_COST_FIELD_NUMBER;
      hash = (53 * hash) + getRemoveCost().hashCode();
    }
    hash = (37 * hash) + LOCKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLocked());
    if (hasPrimaryStat()) {
      hash = (37 * hash) + PRIMARY_STAT_FIELD_NUMBER;
      hash = (53 * hash) + getPrimaryStat().hashCode();
    }
    if (getSecondaryStatCount() > 0) {
      hash = (37 * hash) + SECONDARY_STAT_FIELD_NUMBER;
      hash = (53 * hash) + getSecondaryStatList().hashCode();
    }
    hash = (37 * hash) + XP_FIELD_NUMBER;
    hash = (53 * hash) + getXp();
    if (hasLevelCost()) {
      hash = (37 * hash) + LEVEL_COST_FIELD_NUMBER;
      hash = (53 * hash) + getLevelCost().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StatMod parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StatMod parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StatMod parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StatMod parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StatMod parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StatMod parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StatMod parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StatMod parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StatMod parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StatMod parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StatMod parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StatMod parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StatMod prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code serenno.protos.playerProfileResponse.StatMod}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serenno.protos.playerProfileResponse.StatMod)
      StatModOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_StatMod_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_StatMod_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StatMod.class, Builder.class);
    }

    // Construct using serenno.protos.playerProfileResponse.StatMod.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSecondaryStatFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = "";

      definitionId_ = "";

      level_ = 0;

      tier_ = 0;

      if (sellValueBuilder_ == null) {
        sellValue_ = null;
      } else {
        sellValue_ = null;
        sellValueBuilder_ = null;
      }
      if (removeCostBuilder_ == null) {
        removeCost_ = null;
      } else {
        removeCost_ = null;
        removeCostBuilder_ = null;
      }
      locked_ = false;

      if (primaryStatBuilder_ == null) {
        primaryStat_ = null;
      } else {
        primaryStat_ = null;
        primaryStatBuilder_ = null;
      }
      if (secondaryStatBuilder_ == null) {
        secondaryStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        secondaryStatBuilder_.clear();
      }
      xp_ = 0;

      if (levelCostBuilder_ == null) {
        levelCost_ = null;
      } else {
        levelCost_ = null;
        levelCostBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_StatMod_descriptor;
    }

    @Override
    public StatMod getDefaultInstanceForType() {
      return StatMod.getDefaultInstance();
    }

    @Override
    public StatMod build() {
      StatMod result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StatMod buildPartial() {
      StatMod result = new StatMod(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.definitionId_ = definitionId_;
      result.level_ = level_;
      result.tier_ = tier_;
      if (sellValueBuilder_ == null) {
        result.sellValue_ = sellValue_;
      } else {
        result.sellValue_ = sellValueBuilder_.build();
      }
      if (removeCostBuilder_ == null) {
        result.removeCost_ = removeCost_;
      } else {
        result.removeCost_ = removeCostBuilder_.build();
      }
      result.locked_ = locked_;
      if (primaryStatBuilder_ == null) {
        result.primaryStat_ = primaryStat_;
      } else {
        result.primaryStat_ = primaryStatBuilder_.build();
      }
      if (secondaryStatBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          secondaryStat_ = java.util.Collections.unmodifiableList(secondaryStat_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.secondaryStat_ = secondaryStat_;
      } else {
        result.secondaryStat_ = secondaryStatBuilder_.build();
      }
      result.xp_ = xp_;
      if (levelCostBuilder_ == null) {
        result.levelCost_ = levelCost_;
      } else {
        result.levelCost_ = levelCostBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StatMod) {
        return mergeFrom((StatMod)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StatMod other) {
      if (other == StatMod.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getDefinitionId().isEmpty()) {
        definitionId_ = other.definitionId_;
        onChanged();
      }
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (other.tier_ != 0) {
        setTierValue(other.getTierValue());
      }
      if (other.hasSellValue()) {
        mergeSellValue(other.getSellValue());
      }
      if (other.hasRemoveCost()) {
        mergeRemoveCost(other.getRemoveCost());
      }
      if (other.getLocked() != false) {
        setLocked(other.getLocked());
      }
      if (other.hasPrimaryStat()) {
        mergePrimaryStat(other.getPrimaryStat());
      }
      if (secondaryStatBuilder_ == null) {
        if (!other.secondaryStat_.isEmpty()) {
          if (secondaryStat_.isEmpty()) {
            secondaryStat_ = other.secondaryStat_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSecondaryStatIsMutable();
            secondaryStat_.addAll(other.secondaryStat_);
          }
          onChanged();
        }
      } else {
        if (!other.secondaryStat_.isEmpty()) {
          if (secondaryStatBuilder_.isEmpty()) {
            secondaryStatBuilder_.dispose();
            secondaryStatBuilder_ = null;
            secondaryStat_ = other.secondaryStat_;
            bitField0_ = (bitField0_ & ~0x00000001);
            secondaryStatBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSecondaryStatFieldBuilder() : null;
          } else {
            secondaryStatBuilder_.addAllMessages(other.secondaryStat_);
          }
        }
      }
      if (other.getXp() != 0) {
        setXp(other.getXp());
      }
      if (other.hasLevelCost()) {
        mergeLevelCost(other.getLevelCost());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StatMod parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StatMod) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private Object definitionId_ = "";
    /**
     * <code>string definition_id = 2;</code>
     * @return The definitionId.
     */
    public String getDefinitionId() {
      Object ref = definitionId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        definitionId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string definition_id = 2;</code>
     * @return The bytes for definitionId.
     */
    public com.google.protobuf.ByteString
        getDefinitionIdBytes() {
      Object ref = definitionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        definitionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string definition_id = 2;</code>
     * @param value The definitionId to set.
     * @return This builder for chaining.
     */
    public Builder setDefinitionId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      definitionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string definition_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefinitionId() {
      
      definitionId_ = getDefaultInstance().getDefinitionId();
      onChanged();
      return this;
    }
    /**
     * <code>string definition_id = 2;</code>
     * @param value The bytes for definitionId to set.
     * @return This builder for chaining.
     */
    public Builder setDefinitionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      definitionId_ = value;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <code>int32 level = 4;</code>
     * @return The level.
     */
    @Override
    public int getLevel() {
      return level_;
    }
    /**
     * <code>int32 level = 4;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {
      
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 level = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      
      level_ = 0;
      onChanged();
      return this;
    }

    private int tier_ = 0;
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModTier tier = 5;</code>
     * @return The enum numeric value on the wire for tier.
     */
    @Override public int getTierValue() {
      return tier_;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModTier tier = 5;</code>
     * @param value The enum numeric value on the wire for tier to set.
     * @return This builder for chaining.
     */
    public Builder setTierValue(int value) {
      
      tier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModTier tier = 5;</code>
     * @return The tier.
     */
    @Override
    public StatModTier getTier() {
      @SuppressWarnings("deprecation")
      StatModTier result = StatModTier.valueOf(tier_);
      return result == null ? StatModTier.UNRECOGNIZED : result;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModTier tier = 5;</code>
     * @param value The tier to set.
     * @return This builder for chaining.
     */
    public Builder setTier(StatModTier value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      tier_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModTier tier = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTier() {
      
      tier_ = 0;
      onChanged();
      return this;
    }

    private CurrencyItem sellValue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder> sellValueBuilder_;
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     * @return Whether the sellValue field is set.
     */
    public boolean hasSellValue() {
      return sellValueBuilder_ != null || sellValue_ != null;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     * @return The sellValue.
     */
    public CurrencyItem getSellValue() {
      if (sellValueBuilder_ == null) {
        return sellValue_ == null ? CurrencyItem.getDefaultInstance() : sellValue_;
      } else {
        return sellValueBuilder_.getMessage();
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     */
    public Builder setSellValue(CurrencyItem value) {
      if (sellValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sellValue_ = value;
        onChanged();
      } else {
        sellValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     */
    public Builder setSellValue(
        CurrencyItem.Builder builderForValue) {
      if (sellValueBuilder_ == null) {
        sellValue_ = builderForValue.build();
        onChanged();
      } else {
        sellValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     */
    public Builder mergeSellValue(CurrencyItem value) {
      if (sellValueBuilder_ == null) {
        if (sellValue_ != null) {
          sellValue_ =
            CurrencyItem.newBuilder(sellValue_).mergeFrom(value).buildPartial();
        } else {
          sellValue_ = value;
        }
        onChanged();
      } else {
        sellValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     */
    public Builder clearSellValue() {
      if (sellValueBuilder_ == null) {
        sellValue_ = null;
        onChanged();
      } else {
        sellValue_ = null;
        sellValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     */
    public CurrencyItem.Builder getSellValueBuilder() {
      
      onChanged();
      return getSellValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     */
    public CurrencyItemOrBuilder getSellValueOrBuilder() {
      if (sellValueBuilder_ != null) {
        return sellValueBuilder_.getMessageOrBuilder();
      } else {
        return sellValue_ == null ?
            CurrencyItem.getDefaultInstance() : sellValue_;
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem sell_value = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder>
        getSellValueFieldBuilder() {
      if (sellValueBuilder_ == null) {
        sellValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder>(
                getSellValue(),
                getParentForChildren(),
                isClean());
        sellValue_ = null;
      }
      return sellValueBuilder_;
    }

    private CurrencyItem removeCost_;
    private com.google.protobuf.SingleFieldBuilderV3<
        CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder> removeCostBuilder_;
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     * @return Whether the removeCost field is set.
     */
    public boolean hasRemoveCost() {
      return removeCostBuilder_ != null || removeCost_ != null;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     * @return The removeCost.
     */
    public CurrencyItem getRemoveCost() {
      if (removeCostBuilder_ == null) {
        return removeCost_ == null ? CurrencyItem.getDefaultInstance() : removeCost_;
      } else {
        return removeCostBuilder_.getMessage();
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     */
    public Builder setRemoveCost(CurrencyItem value) {
      if (removeCostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        removeCost_ = value;
        onChanged();
      } else {
        removeCostBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     */
    public Builder setRemoveCost(
        CurrencyItem.Builder builderForValue) {
      if (removeCostBuilder_ == null) {
        removeCost_ = builderForValue.build();
        onChanged();
      } else {
        removeCostBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     */
    public Builder mergeRemoveCost(CurrencyItem value) {
      if (removeCostBuilder_ == null) {
        if (removeCost_ != null) {
          removeCost_ =
            CurrencyItem.newBuilder(removeCost_).mergeFrom(value).buildPartial();
        } else {
          removeCost_ = value;
        }
        onChanged();
      } else {
        removeCostBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     */
    public Builder clearRemoveCost() {
      if (removeCostBuilder_ == null) {
        removeCost_ = null;
        onChanged();
      } else {
        removeCost_ = null;
        removeCostBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     */
    public CurrencyItem.Builder getRemoveCostBuilder() {
      
      onChanged();
      return getRemoveCostFieldBuilder().getBuilder();
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     */
    public CurrencyItemOrBuilder getRemoveCostOrBuilder() {
      if (removeCostBuilder_ != null) {
        return removeCostBuilder_.getMessageOrBuilder();
      } else {
        return removeCost_ == null ?
            CurrencyItem.getDefaultInstance() : removeCost_;
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem remove_cost = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder>
        getRemoveCostFieldBuilder() {
      if (removeCostBuilder_ == null) {
        removeCostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder>(
                getRemoveCost(),
                getParentForChildren(),
                isClean());
        removeCost_ = null;
      }
      return removeCostBuilder_;
    }

    private boolean locked_ ;
    /**
     * <code>bool locked = 11;</code>
     * @return The locked.
     */
    @Override
    public boolean getLocked() {
      return locked_;
    }
    /**
     * <code>bool locked = 11;</code>
     * @param value The locked to set.
     * @return This builder for chaining.
     */
    public Builder setLocked(boolean value) {
      
      locked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool locked = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocked() {
      
      locked_ = false;
      onChanged();
      return this;
    }

    private StatModStat primaryStat_;
    private com.google.protobuf.SingleFieldBuilderV3<
        StatModStat, StatModStat.Builder, StatModStatOrBuilder> primaryStatBuilder_;
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     * @return Whether the primaryStat field is set.
     */
    public boolean hasPrimaryStat() {
      return primaryStatBuilder_ != null || primaryStat_ != null;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     * @return The primaryStat.
     */
    public StatModStat getPrimaryStat() {
      if (primaryStatBuilder_ == null) {
        return primaryStat_ == null ? StatModStat.getDefaultInstance() : primaryStat_;
      } else {
        return primaryStatBuilder_.getMessage();
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     */
    public Builder setPrimaryStat(StatModStat value) {
      if (primaryStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        primaryStat_ = value;
        onChanged();
      } else {
        primaryStatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     */
    public Builder setPrimaryStat(
        StatModStat.Builder builderForValue) {
      if (primaryStatBuilder_ == null) {
        primaryStat_ = builderForValue.build();
        onChanged();
      } else {
        primaryStatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     */
    public Builder mergePrimaryStat(StatModStat value) {
      if (primaryStatBuilder_ == null) {
        if (primaryStat_ != null) {
          primaryStat_ =
            StatModStat.newBuilder(primaryStat_).mergeFrom(value).buildPartial();
        } else {
          primaryStat_ = value;
        }
        onChanged();
      } else {
        primaryStatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     */
    public Builder clearPrimaryStat() {
      if (primaryStatBuilder_ == null) {
        primaryStat_ = null;
        onChanged();
      } else {
        primaryStat_ = null;
        primaryStatBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     */
    public StatModStat.Builder getPrimaryStatBuilder() {
      
      onChanged();
      return getPrimaryStatFieldBuilder().getBuilder();
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     */
    public StatModStatOrBuilder getPrimaryStatOrBuilder() {
      if (primaryStatBuilder_ != null) {
        return primaryStatBuilder_.getMessageOrBuilder();
      } else {
        return primaryStat_ == null ?
            StatModStat.getDefaultInstance() : primaryStat_;
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatModStat primary_stat = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        StatModStat, StatModStat.Builder, StatModStatOrBuilder>
        getPrimaryStatFieldBuilder() {
      if (primaryStatBuilder_ == null) {
        primaryStatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            StatModStat, StatModStat.Builder, StatModStatOrBuilder>(
                getPrimaryStat(),
                getParentForChildren(),
                isClean());
        primaryStat_ = null;
      }
      return primaryStatBuilder_;
    }

    private java.util.List<StatModStat> secondaryStat_ =
      java.util.Collections.emptyList();
    private void ensureSecondaryStatIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        secondaryStat_ = new java.util.ArrayList<StatModStat>(secondaryStat_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        StatModStat, StatModStat.Builder, StatModStatOrBuilder> secondaryStatBuilder_;

    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public java.util.List<StatModStat> getSecondaryStatList() {
      if (secondaryStatBuilder_ == null) {
        return java.util.Collections.unmodifiableList(secondaryStat_);
      } else {
        return secondaryStatBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public int getSecondaryStatCount() {
      if (secondaryStatBuilder_ == null) {
        return secondaryStat_.size();
      } else {
        return secondaryStatBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public StatModStat getSecondaryStat(int index) {
      if (secondaryStatBuilder_ == null) {
        return secondaryStat_.get(index);
      } else {
        return secondaryStatBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder setSecondaryStat(
        int index, StatModStat value) {
      if (secondaryStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecondaryStatIsMutable();
        secondaryStat_.set(index, value);
        onChanged();
      } else {
        secondaryStatBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder setSecondaryStat(
        int index, StatModStat.Builder builderForValue) {
      if (secondaryStatBuilder_ == null) {
        ensureSecondaryStatIsMutable();
        secondaryStat_.set(index, builderForValue.build());
        onChanged();
      } else {
        secondaryStatBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder addSecondaryStat(StatModStat value) {
      if (secondaryStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecondaryStatIsMutable();
        secondaryStat_.add(value);
        onChanged();
      } else {
        secondaryStatBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder addSecondaryStat(
        int index, StatModStat value) {
      if (secondaryStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSecondaryStatIsMutable();
        secondaryStat_.add(index, value);
        onChanged();
      } else {
        secondaryStatBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder addSecondaryStat(
        StatModStat.Builder builderForValue) {
      if (secondaryStatBuilder_ == null) {
        ensureSecondaryStatIsMutable();
        secondaryStat_.add(builderForValue.build());
        onChanged();
      } else {
        secondaryStatBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder addSecondaryStat(
        int index, StatModStat.Builder builderForValue) {
      if (secondaryStatBuilder_ == null) {
        ensureSecondaryStatIsMutable();
        secondaryStat_.add(index, builderForValue.build());
        onChanged();
      } else {
        secondaryStatBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder addAllSecondaryStat(
        Iterable<? extends StatModStat> values) {
      if (secondaryStatBuilder_ == null) {
        ensureSecondaryStatIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, secondaryStat_);
        onChanged();
      } else {
        secondaryStatBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder clearSecondaryStat() {
      if (secondaryStatBuilder_ == null) {
        secondaryStat_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        secondaryStatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public Builder removeSecondaryStat(int index) {
      if (secondaryStatBuilder_ == null) {
        ensureSecondaryStatIsMutable();
        secondaryStat_.remove(index);
        onChanged();
      } else {
        secondaryStatBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public StatModStat.Builder getSecondaryStatBuilder(
        int index) {
      return getSecondaryStatFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public StatModStatOrBuilder getSecondaryStatOrBuilder(
        int index) {
      if (secondaryStatBuilder_ == null) {
        return secondaryStat_.get(index);  } else {
        return secondaryStatBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public java.util.List<? extends StatModStatOrBuilder>
         getSecondaryStatOrBuilderList() {
      if (secondaryStatBuilder_ != null) {
        return secondaryStatBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(secondaryStat_);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public StatModStat.Builder addSecondaryStatBuilder() {
      return getSecondaryStatFieldBuilder().addBuilder(
          StatModStat.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public StatModStat.Builder addSecondaryStatBuilder(
        int index) {
      return getSecondaryStatFieldBuilder().addBuilder(
          index, StatModStat.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatModStat secondary_stat = 13;</code>
     */
    public java.util.List<StatModStat.Builder>
         getSecondaryStatBuilderList() {
      return getSecondaryStatFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        StatModStat, StatModStat.Builder, StatModStatOrBuilder>
        getSecondaryStatFieldBuilder() {
      if (secondaryStatBuilder_ == null) {
        secondaryStatBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            StatModStat, StatModStat.Builder, StatModStatOrBuilder>(
                secondaryStat_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        secondaryStat_ = null;
      }
      return secondaryStatBuilder_;
    }

    private int xp_ ;
    /**
     * <code>int32 xp = 14;</code>
     * @return The xp.
     */
    @Override
    public int getXp() {
      return xp_;
    }
    /**
     * <code>int32 xp = 14;</code>
     * @param value The xp to set.
     * @return This builder for chaining.
     */
    public Builder setXp(int value) {
      
      xp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 xp = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearXp() {
      
      xp_ = 0;
      onChanged();
      return this;
    }

    private CurrencyItem levelCost_;
    private com.google.protobuf.SingleFieldBuilderV3<
        CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder> levelCostBuilder_;
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     * @return Whether the levelCost field is set.
     */
    public boolean hasLevelCost() {
      return levelCostBuilder_ != null || levelCost_ != null;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     * @return The levelCost.
     */
    public CurrencyItem getLevelCost() {
      if (levelCostBuilder_ == null) {
        return levelCost_ == null ? CurrencyItem.getDefaultInstance() : levelCost_;
      } else {
        return levelCostBuilder_.getMessage();
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     */
    public Builder setLevelCost(CurrencyItem value) {
      if (levelCostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        levelCost_ = value;
        onChanged();
      } else {
        levelCostBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     */
    public Builder setLevelCost(
        CurrencyItem.Builder builderForValue) {
      if (levelCostBuilder_ == null) {
        levelCost_ = builderForValue.build();
        onChanged();
      } else {
        levelCostBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     */
    public Builder mergeLevelCost(CurrencyItem value) {
      if (levelCostBuilder_ == null) {
        if (levelCost_ != null) {
          levelCost_ =
            CurrencyItem.newBuilder(levelCost_).mergeFrom(value).buildPartial();
        } else {
          levelCost_ = value;
        }
        onChanged();
      } else {
        levelCostBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     */
    public Builder clearLevelCost() {
      if (levelCostBuilder_ == null) {
        levelCost_ = null;
        onChanged();
      } else {
        levelCost_ = null;
        levelCostBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     */
    public CurrencyItem.Builder getLevelCostBuilder() {
      
      onChanged();
      return getLevelCostFieldBuilder().getBuilder();
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     */
    public CurrencyItemOrBuilder getLevelCostOrBuilder() {
      if (levelCostBuilder_ != null) {
        return levelCostBuilder_.getMessageOrBuilder();
      } else {
        return levelCost_ == null ?
            CurrencyItem.getDefaultInstance() : levelCost_;
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.CurrencyItem level_cost = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder>
        getLevelCostFieldBuilder() {
      if (levelCostBuilder_ == null) {
        levelCostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            CurrencyItem, CurrencyItem.Builder, CurrencyItemOrBuilder>(
                getLevelCost(),
                getParentForChildren(),
                isClean());
        levelCost_ = null;
      }
      return levelCostBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:serenno.protos.playerProfileResponse.StatMod)
  }

  // @@protoc_insertion_point(class_scope:serenno.protos.playerProfileResponse.StatMod)
  private static final StatMod DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StatMod();
  }

  public static StatMod getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatMod>
      PARSER = new com.google.protobuf.AbstractParser<StatMod>() {
    @Override
    public StatMod parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StatMod(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StatMod> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StatMod> getParserForType() {
    return PARSER;
  }

  @Override
  public StatMod getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

