// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

public interface StatModStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.playerProfileResponse.StatModStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string updater_id = 1;</code>
   * @return The updaterId.
   */
  String getUpdaterId();
  /**
   * <code>string updater_id = 1;</code>
   * @return The bytes for updaterId.
   */
  com.google.protobuf.ByteString
      getUpdaterIdBytes();

  /**
   * <code>.serenno.protos.playerProfileResponse.Stat stat = 2;</code>
   * @return Whether the stat field is set.
   */
  boolean hasStat();
  /**
   * <code>.serenno.protos.playerProfileResponse.Stat stat = 2;</code>
   * @return The stat.
   */
  Stat getStat();
  /**
   * <code>.serenno.protos.playerProfileResponse.Stat stat = 2;</code>
   */
  StatOrBuilder getStatOrBuilder();

  /**
   * <code>repeated string roll = 3;</code>
   * @return A list containing the roll.
   */
  java.util.List<String>
      getRollList();
  /**
   * <code>repeated string roll = 3;</code>
   * @return The count of roll.
   */
  int getRollCount();
  /**
   * <code>repeated string roll = 3;</code>
   * @param index The index of the element to return.
   * @return The roll at the given index.
   */
  String getRoll(int index);
  /**
   * <code>repeated string roll = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the roll at the given index.
   */
  com.google.protobuf.ByteString
      getRollBytes(int index);
}
