// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

public interface StatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.playerProfileResponse.Stat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stat_id = 1;</code>
   * @return The statId.
   */
  String getStatId();
  /**
   * <code>string stat_id = 1;</code>
   * @return The bytes for statId.
   */
  com.google.protobuf.ByteString
      getStatIdBytes();

  /**
   * <code>.serenno.protos.playerProfileResponse.UnitStat unit_stat_id = 3;</code>
   * @return The enum numeric value on the wire for unitStatId.
   */
  int getUnitStatIdValue();
  /**
   * <code>.serenno.protos.playerProfileResponse.UnitStat unit_stat_id = 3;</code>
   * @return The unitStatId.
   */
  UnitStat getUnitStatId();

  /**
   * <code>int32 stat_value_decimal_old = 4;</code>
   * @return The statValueDecimalOld.
   */
  int getStatValueDecimalOld();

  /**
   * <code>int64 stat_value_decimal = 5;</code>
   * @return The statValueDecimal.
   */
  long getStatValueDecimal();
}
