// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

/**
 * Protobuf type {@code serenno.protos.playerProfileResponse.Unit}
 */
public final class Unit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serenno.protos.playerProfileResponse.Unit)
    UnitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Unit.newBuilder() to construct.
  private Unit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Unit() {
    id_ = "";
    definitionId_ = "";
    currentRarity_ = 0;
    promotionRecipeReference_ = "";
    skill_ = java.util.Collections.emptyList();
    equipment_ = java.util.Collections.emptyList();
    currentTier_ = 0;
    equippedStatModOld_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    equippedStatMod_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Unit();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Unit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            definitionId_ = s;
            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            currentRarity_ = rawValue;
            break;
          }
          case 72: {

            currentLevel_ = input.readInt32();
            break;
          }
          case 80: {

            currentXp_ = input.readInt32();
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            promotionRecipeReference_ = s;
            break;
          }
          case 130: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              skill_ = new java.util.ArrayList<Skill>();
              mutable_bitField0_ |= 0x00000001;
            }
            skill_.add(
                input.readMessage(Skill.parser(), extensionRegistry));
            break;
          }
          case 138: {
            StatDef.Builder subBuilder = null;
            if (unitStat_ != null) {
              subBuilder = unitStat_.toBuilder();
            }
            unitStat_ = input.readMessage(StatDef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(unitStat_);
              unitStat_ = subBuilder.buildPartial();
            }

            break;
          }
          case 146: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              equipment_ = new java.util.ArrayList<EquipmentSlot>();
              mutable_bitField0_ |= 0x00000002;
            }
            equipment_.add(
                input.readMessage(EquipmentSlot.parser(), extensionRegistry));
            break;
          }
          case 152: {
            int rawValue = input.readEnum();

            currentTier_ = rawValue;
            break;
          }
          case 162: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              equippedStatModOld_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            equippedStatModOld_.add(s);
            break;
          }
          case 170: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              equippedStatMod_ = new java.util.ArrayList<StatMod>();
              mutable_bitField0_ |= 0x00000008;
            }
            equippedStatMod_.add(
                input.readMessage(StatMod.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        skill_ = java.util.Collections.unmodifiableList(skill_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        equipment_ = java.util.Collections.unmodifiableList(equipment_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        equippedStatModOld_ = equippedStatModOld_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        equippedStatMod_ = java.util.Collections.unmodifiableList(equippedStatMod_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_Unit_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_Unit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Unit.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFINITION_ID_FIELD_NUMBER = 2;
  private volatile Object definitionId_;
  /**
   * <code>string definition_id = 2;</code>
   * @return The definitionId.
   */
  @Override
  public String getDefinitionId() {
    Object ref = definitionId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      definitionId_ = s;
      return s;
    }
  }
  /**
   * <code>string definition_id = 2;</code>
   * @return The bytes for definitionId.
   */
  @Override
  public com.google.protobuf.ByteString
      getDefinitionIdBytes() {
    Object ref = definitionId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      definitionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_RARITY_FIELD_NUMBER = 8;
  private int currentRarity_;
  /**
   * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
   * @return The enum numeric value on the wire for currentRarity.
   */
  @Override public int getCurrentRarityValue() {
    return currentRarity_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
   * @return The currentRarity.
   */
  @Override public Rarity getCurrentRarity() {
    @SuppressWarnings("deprecation")
    Rarity result = Rarity.valueOf(currentRarity_);
    return result == null ? Rarity.UNRECOGNIZED : result;
  }

  public static final int CURRENT_LEVEL_FIELD_NUMBER = 9;
  private int currentLevel_;
  /**
   * <code>int32 current_level = 9;</code>
   * @return The currentLevel.
   */
  @Override
  public int getCurrentLevel() {
    return currentLevel_;
  }

  public static final int CURRENT_XP_FIELD_NUMBER = 10;
  private int currentXp_;
  /**
   * <code>int32 current_xp = 10;</code>
   * @return The currentXp.
   */
  @Override
  public int getCurrentXp() {
    return currentXp_;
  }

  public static final int PROMOTION_RECIPE_REFERENCE_FIELD_NUMBER = 12;
  private volatile Object promotionRecipeReference_;
  /**
   * <code>string promotion_recipe_reference = 12;</code>
   * @return The promotionRecipeReference.
   */
  @Override
  public String getPromotionRecipeReference() {
    Object ref = promotionRecipeReference_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      promotionRecipeReference_ = s;
      return s;
    }
  }
  /**
   * <code>string promotion_recipe_reference = 12;</code>
   * @return The bytes for promotionRecipeReference.
   */
  @Override
  public com.google.protobuf.ByteString
      getPromotionRecipeReferenceBytes() {
    Object ref = promotionRecipeReference_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      promotionRecipeReference_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKILL_FIELD_NUMBER = 16;
  private java.util.List<Skill> skill_;
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  @Override
  public java.util.List<Skill> getSkillList() {
    return skill_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  @Override
  public java.util.List<? extends SkillOrBuilder>
      getSkillOrBuilderList() {
    return skill_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  @Override
  public int getSkillCount() {
    return skill_.size();
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  @Override
  public Skill getSkill(int index) {
    return skill_.get(index);
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  @Override
  public SkillOrBuilder getSkillOrBuilder(
      int index) {
    return skill_.get(index);
  }

  public static final int UNIT_STAT_FIELD_NUMBER = 17;
  private StatDef unitStat_;
  /**
   * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
   * @return Whether the unitStat field is set.
   */
  @Override
  public boolean hasUnitStat() {
    return unitStat_ != null;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
   * @return The unitStat.
   */
  @Override
  public StatDef getUnitStat() {
    return unitStat_ == null ? StatDef.getDefaultInstance() : unitStat_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
   */
  @Override
  public StatDefOrBuilder getUnitStatOrBuilder() {
    return getUnitStat();
  }

  public static final int EQUIPMENT_FIELD_NUMBER = 18;
  private java.util.List<EquipmentSlot> equipment_;
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  @Override
  public java.util.List<EquipmentSlot> getEquipmentList() {
    return equipment_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  @Override
  public java.util.List<? extends EquipmentSlotOrBuilder>
      getEquipmentOrBuilderList() {
    return equipment_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  @Override
  public int getEquipmentCount() {
    return equipment_.size();
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  @Override
  public EquipmentSlot getEquipment(int index) {
    return equipment_.get(index);
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  @Override
  public EquipmentSlotOrBuilder getEquipmentOrBuilder(
      int index) {
    return equipment_.get(index);
  }

  public static final int CURRENT_TIER_FIELD_NUMBER = 19;
  private int currentTier_;
  /**
   * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
   * @return The enum numeric value on the wire for currentTier.
   */
  @Override public int getCurrentTierValue() {
    return currentTier_;
  }
  /**
   * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
   * @return The currentTier.
   */
  @Override public UnitTier getCurrentTier() {
    @SuppressWarnings("deprecation")
    UnitTier result = UnitTier.valueOf(currentTier_);
    return result == null ? UnitTier.UNRECOGNIZED : result;
  }

  public static final int EQUIPPED_STAT_MOD_OLD_FIELD_NUMBER = 20;
  private com.google.protobuf.LazyStringList equippedStatModOld_;
  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @return A list containing the equippedStatModOld.
   */
  public com.google.protobuf.ProtocolStringList
      getEquippedStatModOldList() {
    return equippedStatModOld_;
  }
  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @return The count of equippedStatModOld.
   */
  public int getEquippedStatModOldCount() {
    return equippedStatModOld_.size();
  }
  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @param index The index of the element to return.
   * @return The equippedStatModOld at the given index.
   */
  public String getEquippedStatModOld(int index) {
    return equippedStatModOld_.get(index);
  }
  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @param index The index of the value to return.
   * @return The bytes of the equippedStatModOld at the given index.
   */
  public com.google.protobuf.ByteString
      getEquippedStatModOldBytes(int index) {
    return equippedStatModOld_.getByteString(index);
  }

  public static final int EQUIPPED_STAT_MOD_FIELD_NUMBER = 21;
  private java.util.List<StatMod> equippedStatMod_;
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  @Override
  public java.util.List<StatMod> getEquippedStatModList() {
    return equippedStatMod_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  @Override
  public java.util.List<? extends StatModOrBuilder>
      getEquippedStatModOrBuilderList() {
    return equippedStatMod_;
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  @Override
  public int getEquippedStatModCount() {
    return equippedStatMod_.size();
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  @Override
  public StatMod getEquippedStatMod(int index) {
    return equippedStatMod_.get(index);
  }
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  @Override
  public StatModOrBuilder getEquippedStatModOrBuilder(
      int index) {
    return equippedStatMod_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getDefinitionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, definitionId_);
    }
    if (currentRarity_ != Rarity.ZERO_STAR.getNumber()) {
      output.writeEnum(8, currentRarity_);
    }
    if (currentLevel_ != 0) {
      output.writeInt32(9, currentLevel_);
    }
    if (currentXp_ != 0) {
      output.writeInt32(10, currentXp_);
    }
    if (!getPromotionRecipeReferenceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, promotionRecipeReference_);
    }
    for (int i = 0; i < skill_.size(); i++) {
      output.writeMessage(16, skill_.get(i));
    }
    if (unitStat_ != null) {
      output.writeMessage(17, getUnitStat());
    }
    for (int i = 0; i < equipment_.size(); i++) {
      output.writeMessage(18, equipment_.get(i));
    }
    if (currentTier_ != UnitTier.TIER_00.getNumber()) {
      output.writeEnum(19, currentTier_);
    }
    for (int i = 0; i < equippedStatModOld_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, equippedStatModOld_.getRaw(i));
    }
    for (int i = 0; i < equippedStatMod_.size(); i++) {
      output.writeMessage(21, equippedStatMod_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getDefinitionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, definitionId_);
    }
    if (currentRarity_ != Rarity.ZERO_STAR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, currentRarity_);
    }
    if (currentLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, currentLevel_);
    }
    if (currentXp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, currentXp_);
    }
    if (!getPromotionRecipeReferenceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, promotionRecipeReference_);
    }
    for (int i = 0; i < skill_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, skill_.get(i));
    }
    if (unitStat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getUnitStat());
    }
    for (int i = 0; i < equipment_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(18, equipment_.get(i));
    }
    if (currentTier_ != UnitTier.TIER_00.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(19, currentTier_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < equippedStatModOld_.size(); i++) {
        dataSize += computeStringSizeNoTag(equippedStatModOld_.getRaw(i));
      }
      size += dataSize;
      size += 2 * getEquippedStatModOldList().size();
    }
    for (int i = 0; i < equippedStatMod_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, equippedStatMod_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Unit)) {
      return super.equals(obj);
    }
    Unit other = (Unit) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getDefinitionId()
        .equals(other.getDefinitionId())) return false;
    if (currentRarity_ != other.currentRarity_) return false;
    if (getCurrentLevel()
        != other.getCurrentLevel()) return false;
    if (getCurrentXp()
        != other.getCurrentXp()) return false;
    if (!getPromotionRecipeReference()
        .equals(other.getPromotionRecipeReference())) return false;
    if (!getSkillList()
        .equals(other.getSkillList())) return false;
    if (hasUnitStat() != other.hasUnitStat()) return false;
    if (hasUnitStat()) {
      if (!getUnitStat()
          .equals(other.getUnitStat())) return false;
    }
    if (!getEquipmentList()
        .equals(other.getEquipmentList())) return false;
    if (currentTier_ != other.currentTier_) return false;
    if (!getEquippedStatModOldList()
        .equals(other.getEquippedStatModOldList())) return false;
    if (!getEquippedStatModList()
        .equals(other.getEquippedStatModList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + DEFINITION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDefinitionId().hashCode();
    hash = (37 * hash) + CURRENT_RARITY_FIELD_NUMBER;
    hash = (53 * hash) + currentRarity_;
    hash = (37 * hash) + CURRENT_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentLevel();
    hash = (37 * hash) + CURRENT_XP_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentXp();
    hash = (37 * hash) + PROMOTION_RECIPE_REFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + getPromotionRecipeReference().hashCode();
    if (getSkillCount() > 0) {
      hash = (37 * hash) + SKILL_FIELD_NUMBER;
      hash = (53 * hash) + getSkillList().hashCode();
    }
    if (hasUnitStat()) {
      hash = (37 * hash) + UNIT_STAT_FIELD_NUMBER;
      hash = (53 * hash) + getUnitStat().hashCode();
    }
    if (getEquipmentCount() > 0) {
      hash = (37 * hash) + EQUIPMENT_FIELD_NUMBER;
      hash = (53 * hash) + getEquipmentList().hashCode();
    }
    hash = (37 * hash) + CURRENT_TIER_FIELD_NUMBER;
    hash = (53 * hash) + currentTier_;
    if (getEquippedStatModOldCount() > 0) {
      hash = (37 * hash) + EQUIPPED_STAT_MOD_OLD_FIELD_NUMBER;
      hash = (53 * hash) + getEquippedStatModOldList().hashCode();
    }
    if (getEquippedStatModCount() > 0) {
      hash = (37 * hash) + EQUIPPED_STAT_MOD_FIELD_NUMBER;
      hash = (53 * hash) + getEquippedStatModList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Unit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Unit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Unit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Unit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Unit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Unit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Unit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Unit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Unit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Unit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Unit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Unit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Unit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code serenno.protos.playerProfileResponse.Unit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serenno.protos.playerProfileResponse.Unit)
      UnitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_Unit_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_Unit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Unit.class, Builder.class);
    }

    // Construct using serenno.protos.playerProfileResponse.Unit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSkillFieldBuilder();
        getEquipmentFieldBuilder();
        getEquippedStatModFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = "";

      definitionId_ = "";

      currentRarity_ = 0;

      currentLevel_ = 0;

      currentXp_ = 0;

      promotionRecipeReference_ = "";

      if (skillBuilder_ == null) {
        skill_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        skillBuilder_.clear();
      }
      if (unitStatBuilder_ == null) {
        unitStat_ = null;
      } else {
        unitStat_ = null;
        unitStatBuilder_ = null;
      }
      if (equipmentBuilder_ == null) {
        equipment_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        equipmentBuilder_.clear();
      }
      currentTier_ = 0;

      equippedStatModOld_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (equippedStatModBuilder_ == null) {
        equippedStatMod_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        equippedStatModBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PlayerProfileResponseOuterClass.internal_static_serenno_protos_playerProfileResponse_Unit_descriptor;
    }

    @Override
    public Unit getDefaultInstanceForType() {
      return Unit.getDefaultInstance();
    }

    @Override
    public Unit build() {
      Unit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Unit buildPartial() {
      Unit result = new Unit(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.definitionId_ = definitionId_;
      result.currentRarity_ = currentRarity_;
      result.currentLevel_ = currentLevel_;
      result.currentXp_ = currentXp_;
      result.promotionRecipeReference_ = promotionRecipeReference_;
      if (skillBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          skill_ = java.util.Collections.unmodifiableList(skill_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skill_ = skill_;
      } else {
        result.skill_ = skillBuilder_.build();
      }
      if (unitStatBuilder_ == null) {
        result.unitStat_ = unitStat_;
      } else {
        result.unitStat_ = unitStatBuilder_.build();
      }
      if (equipmentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          equipment_ = java.util.Collections.unmodifiableList(equipment_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.equipment_ = equipment_;
      } else {
        result.equipment_ = equipmentBuilder_.build();
      }
      result.currentTier_ = currentTier_;
      if (((bitField0_ & 0x00000004) != 0)) {
        equippedStatModOld_ = equippedStatModOld_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.equippedStatModOld_ = equippedStatModOld_;
      if (equippedStatModBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          equippedStatMod_ = java.util.Collections.unmodifiableList(equippedStatMod_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.equippedStatMod_ = equippedStatMod_;
      } else {
        result.equippedStatMod_ = equippedStatModBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Unit) {
        return mergeFrom((Unit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Unit other) {
      if (other == Unit.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getDefinitionId().isEmpty()) {
        definitionId_ = other.definitionId_;
        onChanged();
      }
      if (other.currentRarity_ != 0) {
        setCurrentRarityValue(other.getCurrentRarityValue());
      }
      if (other.getCurrentLevel() != 0) {
        setCurrentLevel(other.getCurrentLevel());
      }
      if (other.getCurrentXp() != 0) {
        setCurrentXp(other.getCurrentXp());
      }
      if (!other.getPromotionRecipeReference().isEmpty()) {
        promotionRecipeReference_ = other.promotionRecipeReference_;
        onChanged();
      }
      if (skillBuilder_ == null) {
        if (!other.skill_.isEmpty()) {
          if (skill_.isEmpty()) {
            skill_ = other.skill_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillIsMutable();
            skill_.addAll(other.skill_);
          }
          onChanged();
        }
      } else {
        if (!other.skill_.isEmpty()) {
          if (skillBuilder_.isEmpty()) {
            skillBuilder_.dispose();
            skillBuilder_ = null;
            skill_ = other.skill_;
            bitField0_ = (bitField0_ & ~0x00000001);
            skillBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSkillFieldBuilder() : null;
          } else {
            skillBuilder_.addAllMessages(other.skill_);
          }
        }
      }
      if (other.hasUnitStat()) {
        mergeUnitStat(other.getUnitStat());
      }
      if (equipmentBuilder_ == null) {
        if (!other.equipment_.isEmpty()) {
          if (equipment_.isEmpty()) {
            equipment_ = other.equipment_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEquipmentIsMutable();
            equipment_.addAll(other.equipment_);
          }
          onChanged();
        }
      } else {
        if (!other.equipment_.isEmpty()) {
          if (equipmentBuilder_.isEmpty()) {
            equipmentBuilder_.dispose();
            equipmentBuilder_ = null;
            equipment_ = other.equipment_;
            bitField0_ = (bitField0_ & ~0x00000002);
            equipmentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEquipmentFieldBuilder() : null;
          } else {
            equipmentBuilder_.addAllMessages(other.equipment_);
          }
        }
      }
      if (other.currentTier_ != 0) {
        setCurrentTierValue(other.getCurrentTierValue());
      }
      if (!other.equippedStatModOld_.isEmpty()) {
        if (equippedStatModOld_.isEmpty()) {
          equippedStatModOld_ = other.equippedStatModOld_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureEquippedStatModOldIsMutable();
          equippedStatModOld_.addAll(other.equippedStatModOld_);
        }
        onChanged();
      }
      if (equippedStatModBuilder_ == null) {
        if (!other.equippedStatMod_.isEmpty()) {
          if (equippedStatMod_.isEmpty()) {
            equippedStatMod_ = other.equippedStatMod_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureEquippedStatModIsMutable();
            equippedStatMod_.addAll(other.equippedStatMod_);
          }
          onChanged();
        }
      } else {
        if (!other.equippedStatMod_.isEmpty()) {
          if (equippedStatModBuilder_.isEmpty()) {
            equippedStatModBuilder_.dispose();
            equippedStatModBuilder_ = null;
            equippedStatMod_ = other.equippedStatMod_;
            bitField0_ = (bitField0_ & ~0x00000008);
            equippedStatModBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEquippedStatModFieldBuilder() : null;
          } else {
            equippedStatModBuilder_.addAllMessages(other.equippedStatMod_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Unit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Unit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private Object definitionId_ = "";
    /**
     * <code>string definition_id = 2;</code>
     * @return The definitionId.
     */
    public String getDefinitionId() {
      Object ref = definitionId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        definitionId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string definition_id = 2;</code>
     * @return The bytes for definitionId.
     */
    public com.google.protobuf.ByteString
        getDefinitionIdBytes() {
      Object ref = definitionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        definitionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string definition_id = 2;</code>
     * @param value The definitionId to set.
     * @return This builder for chaining.
     */
    public Builder setDefinitionId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      definitionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string definition_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefinitionId() {
      
      definitionId_ = getDefaultInstance().getDefinitionId();
      onChanged();
      return this;
    }
    /**
     * <code>string definition_id = 2;</code>
     * @param value The bytes for definitionId to set.
     * @return This builder for chaining.
     */
    public Builder setDefinitionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      definitionId_ = value;
      onChanged();
      return this;
    }

    private int currentRarity_ = 0;
    /**
     * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
     * @return The enum numeric value on the wire for currentRarity.
     */
    @Override public int getCurrentRarityValue() {
      return currentRarity_;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
     * @param value The enum numeric value on the wire for currentRarity to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentRarityValue(int value) {
      
      currentRarity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
     * @return The currentRarity.
     */
    @Override
    public Rarity getCurrentRarity() {
      @SuppressWarnings("deprecation")
      Rarity result = Rarity.valueOf(currentRarity_);
      return result == null ? Rarity.UNRECOGNIZED : result;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
     * @param value The currentRarity to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentRarity(Rarity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      currentRarity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentRarity() {
      
      currentRarity_ = 0;
      onChanged();
      return this;
    }

    private int currentLevel_ ;
    /**
     * <code>int32 current_level = 9;</code>
     * @return The currentLevel.
     */
    @Override
    public int getCurrentLevel() {
      return currentLevel_;
    }
    /**
     * <code>int32 current_level = 9;</code>
     * @param value The currentLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentLevel(int value) {
      
      currentLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 current_level = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentLevel() {
      
      currentLevel_ = 0;
      onChanged();
      return this;
    }

    private int currentXp_ ;
    /**
     * <code>int32 current_xp = 10;</code>
     * @return The currentXp.
     */
    @Override
    public int getCurrentXp() {
      return currentXp_;
    }
    /**
     * <code>int32 current_xp = 10;</code>
     * @param value The currentXp to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentXp(int value) {
      
      currentXp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 current_xp = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentXp() {
      
      currentXp_ = 0;
      onChanged();
      return this;
    }

    private Object promotionRecipeReference_ = "";
    /**
     * <code>string promotion_recipe_reference = 12;</code>
     * @return The promotionRecipeReference.
     */
    public String getPromotionRecipeReference() {
      Object ref = promotionRecipeReference_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        promotionRecipeReference_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string promotion_recipe_reference = 12;</code>
     * @return The bytes for promotionRecipeReference.
     */
    public com.google.protobuf.ByteString
        getPromotionRecipeReferenceBytes() {
      Object ref = promotionRecipeReference_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        promotionRecipeReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string promotion_recipe_reference = 12;</code>
     * @param value The promotionRecipeReference to set.
     * @return This builder for chaining.
     */
    public Builder setPromotionRecipeReference(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      promotionRecipeReference_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string promotion_recipe_reference = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearPromotionRecipeReference() {
      
      promotionRecipeReference_ = getDefaultInstance().getPromotionRecipeReference();
      onChanged();
      return this;
    }
    /**
     * <code>string promotion_recipe_reference = 12;</code>
     * @param value The bytes for promotionRecipeReference to set.
     * @return This builder for chaining.
     */
    public Builder setPromotionRecipeReferenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      promotionRecipeReference_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Skill> skill_ =
      java.util.Collections.emptyList();
    private void ensureSkillIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        skill_ = new java.util.ArrayList<Skill>(skill_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Skill, Skill.Builder, SkillOrBuilder> skillBuilder_;

    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public java.util.List<Skill> getSkillList() {
      if (skillBuilder_ == null) {
        return java.util.Collections.unmodifiableList(skill_);
      } else {
        return skillBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public int getSkillCount() {
      if (skillBuilder_ == null) {
        return skill_.size();
      } else {
        return skillBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Skill getSkill(int index) {
      if (skillBuilder_ == null) {
        return skill_.get(index);
      } else {
        return skillBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder setSkill(
        int index, Skill value) {
      if (skillBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillIsMutable();
        skill_.set(index, value);
        onChanged();
      } else {
        skillBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder setSkill(
        int index, Skill.Builder builderForValue) {
      if (skillBuilder_ == null) {
        ensureSkillIsMutable();
        skill_.set(index, builderForValue.build());
        onChanged();
      } else {
        skillBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder addSkill(Skill value) {
      if (skillBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillIsMutable();
        skill_.add(value);
        onChanged();
      } else {
        skillBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder addSkill(
        int index, Skill value) {
      if (skillBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillIsMutable();
        skill_.add(index, value);
        onChanged();
      } else {
        skillBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder addSkill(
        Skill.Builder builderForValue) {
      if (skillBuilder_ == null) {
        ensureSkillIsMutable();
        skill_.add(builderForValue.build());
        onChanged();
      } else {
        skillBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder addSkill(
        int index, Skill.Builder builderForValue) {
      if (skillBuilder_ == null) {
        ensureSkillIsMutable();
        skill_.add(index, builderForValue.build());
        onChanged();
      } else {
        skillBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder addAllSkill(
        Iterable<? extends Skill> values) {
      if (skillBuilder_ == null) {
        ensureSkillIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skill_);
        onChanged();
      } else {
        skillBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder clearSkill() {
      if (skillBuilder_ == null) {
        skill_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        skillBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Builder removeSkill(int index) {
      if (skillBuilder_ == null) {
        ensureSkillIsMutable();
        skill_.remove(index);
        onChanged();
      } else {
        skillBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Skill.Builder getSkillBuilder(
        int index) {
      return getSkillFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public SkillOrBuilder getSkillOrBuilder(
        int index) {
      if (skillBuilder_ == null) {
        return skill_.get(index);  } else {
        return skillBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public java.util.List<? extends SkillOrBuilder>
         getSkillOrBuilderList() {
      if (skillBuilder_ != null) {
        return skillBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(skill_);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Skill.Builder addSkillBuilder() {
      return getSkillFieldBuilder().addBuilder(
          Skill.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public Skill.Builder addSkillBuilder(
        int index) {
      return getSkillFieldBuilder().addBuilder(
          index, Skill.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
     */
    public java.util.List<Skill.Builder>
         getSkillBuilderList() {
      return getSkillFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Skill, Skill.Builder, SkillOrBuilder>
        getSkillFieldBuilder() {
      if (skillBuilder_ == null) {
        skillBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Skill, Skill.Builder, SkillOrBuilder>(
                skill_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        skill_ = null;
      }
      return skillBuilder_;
    }

    private StatDef unitStat_;
    private com.google.protobuf.SingleFieldBuilderV3<
        StatDef, StatDef.Builder, StatDefOrBuilder> unitStatBuilder_;
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     * @return Whether the unitStat field is set.
     */
    public boolean hasUnitStat() {
      return unitStatBuilder_ != null || unitStat_ != null;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     * @return The unitStat.
     */
    public StatDef getUnitStat() {
      if (unitStatBuilder_ == null) {
        return unitStat_ == null ? StatDef.getDefaultInstance() : unitStat_;
      } else {
        return unitStatBuilder_.getMessage();
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     */
    public Builder setUnitStat(StatDef value) {
      if (unitStatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unitStat_ = value;
        onChanged();
      } else {
        unitStatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     */
    public Builder setUnitStat(
        StatDef.Builder builderForValue) {
      if (unitStatBuilder_ == null) {
        unitStat_ = builderForValue.build();
        onChanged();
      } else {
        unitStatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     */
    public Builder mergeUnitStat(StatDef value) {
      if (unitStatBuilder_ == null) {
        if (unitStat_ != null) {
          unitStat_ =
            StatDef.newBuilder(unitStat_).mergeFrom(value).buildPartial();
        } else {
          unitStat_ = value;
        }
        onChanged();
      } else {
        unitStatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     */
    public Builder clearUnitStat() {
      if (unitStatBuilder_ == null) {
        unitStat_ = null;
        onChanged();
      } else {
        unitStat_ = null;
        unitStatBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     */
    public StatDef.Builder getUnitStatBuilder() {
      
      onChanged();
      return getUnitStatFieldBuilder().getBuilder();
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     */
    public StatDefOrBuilder getUnitStatOrBuilder() {
      if (unitStatBuilder_ != null) {
        return unitStatBuilder_.getMessageOrBuilder();
      } else {
        return unitStat_ == null ?
            StatDef.getDefaultInstance() : unitStat_;
      }
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        StatDef, StatDef.Builder, StatDefOrBuilder>
        getUnitStatFieldBuilder() {
      if (unitStatBuilder_ == null) {
        unitStatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            StatDef, StatDef.Builder, StatDefOrBuilder>(
                getUnitStat(),
                getParentForChildren(),
                isClean());
        unitStat_ = null;
      }
      return unitStatBuilder_;
    }

    private java.util.List<EquipmentSlot> equipment_ =
      java.util.Collections.emptyList();
    private void ensureEquipmentIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        equipment_ = new java.util.ArrayList<EquipmentSlot>(equipment_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        EquipmentSlot, EquipmentSlot.Builder, EquipmentSlotOrBuilder> equipmentBuilder_;

    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public java.util.List<EquipmentSlot> getEquipmentList() {
      if (equipmentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(equipment_);
      } else {
        return equipmentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public int getEquipmentCount() {
      if (equipmentBuilder_ == null) {
        return equipment_.size();
      } else {
        return equipmentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public EquipmentSlot getEquipment(int index) {
      if (equipmentBuilder_ == null) {
        return equipment_.get(index);
      } else {
        return equipmentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder setEquipment(
        int index, EquipmentSlot value) {
      if (equipmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquipmentIsMutable();
        equipment_.set(index, value);
        onChanged();
      } else {
        equipmentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder setEquipment(
        int index, EquipmentSlot.Builder builderForValue) {
      if (equipmentBuilder_ == null) {
        ensureEquipmentIsMutable();
        equipment_.set(index, builderForValue.build());
        onChanged();
      } else {
        equipmentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder addEquipment(EquipmentSlot value) {
      if (equipmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquipmentIsMutable();
        equipment_.add(value);
        onChanged();
      } else {
        equipmentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder addEquipment(
        int index, EquipmentSlot value) {
      if (equipmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquipmentIsMutable();
        equipment_.add(index, value);
        onChanged();
      } else {
        equipmentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder addEquipment(
        EquipmentSlot.Builder builderForValue) {
      if (equipmentBuilder_ == null) {
        ensureEquipmentIsMutable();
        equipment_.add(builderForValue.build());
        onChanged();
      } else {
        equipmentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder addEquipment(
        int index, EquipmentSlot.Builder builderForValue) {
      if (equipmentBuilder_ == null) {
        ensureEquipmentIsMutable();
        equipment_.add(index, builderForValue.build());
        onChanged();
      } else {
        equipmentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder addAllEquipment(
        Iterable<? extends EquipmentSlot> values) {
      if (equipmentBuilder_ == null) {
        ensureEquipmentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, equipment_);
        onChanged();
      } else {
        equipmentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder clearEquipment() {
      if (equipmentBuilder_ == null) {
        equipment_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        equipmentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public Builder removeEquipment(int index) {
      if (equipmentBuilder_ == null) {
        ensureEquipmentIsMutable();
        equipment_.remove(index);
        onChanged();
      } else {
        equipmentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public EquipmentSlot.Builder getEquipmentBuilder(
        int index) {
      return getEquipmentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public EquipmentSlotOrBuilder getEquipmentOrBuilder(
        int index) {
      if (equipmentBuilder_ == null) {
        return equipment_.get(index);  } else {
        return equipmentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public java.util.List<? extends EquipmentSlotOrBuilder>
         getEquipmentOrBuilderList() {
      if (equipmentBuilder_ != null) {
        return equipmentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(equipment_);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public EquipmentSlot.Builder addEquipmentBuilder() {
      return getEquipmentFieldBuilder().addBuilder(
          EquipmentSlot.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public EquipmentSlot.Builder addEquipmentBuilder(
        int index) {
      return getEquipmentFieldBuilder().addBuilder(
          index, EquipmentSlot.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
     */
    public java.util.List<EquipmentSlot.Builder>
         getEquipmentBuilderList() {
      return getEquipmentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        EquipmentSlot, EquipmentSlot.Builder, EquipmentSlotOrBuilder>
        getEquipmentFieldBuilder() {
      if (equipmentBuilder_ == null) {
        equipmentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            EquipmentSlot, EquipmentSlot.Builder, EquipmentSlotOrBuilder>(
                equipment_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        equipment_ = null;
      }
      return equipmentBuilder_;
    }

    private int currentTier_ = 0;
    /**
     * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
     * @return The enum numeric value on the wire for currentTier.
     */
    @Override public int getCurrentTierValue() {
      return currentTier_;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
     * @param value The enum numeric value on the wire for currentTier to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentTierValue(int value) {
      
      currentTier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
     * @return The currentTier.
     */
    @Override
    public UnitTier getCurrentTier() {
      @SuppressWarnings("deprecation")
      UnitTier result = UnitTier.valueOf(currentTier_);
      return result == null ? UnitTier.UNRECOGNIZED : result;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
     * @param value The currentTier to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentTier(UnitTier value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      currentTier_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentTier() {
      
      currentTier_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList equippedStatModOld_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEquippedStatModOldIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        equippedStatModOld_ = new com.google.protobuf.LazyStringArrayList(equippedStatModOld_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @return A list containing the equippedStatModOld.
     */
    public com.google.protobuf.ProtocolStringList
        getEquippedStatModOldList() {
      return equippedStatModOld_.getUnmodifiableView();
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @return The count of equippedStatModOld.
     */
    public int getEquippedStatModOldCount() {
      return equippedStatModOld_.size();
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @param index The index of the element to return.
     * @return The equippedStatModOld at the given index.
     */
    public String getEquippedStatModOld(int index) {
      return equippedStatModOld_.get(index);
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @param index The index of the value to return.
     * @return The bytes of the equippedStatModOld at the given index.
     */
    public com.google.protobuf.ByteString
        getEquippedStatModOldBytes(int index) {
      return equippedStatModOld_.getByteString(index);
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @param index The index to set the value at.
     * @param value The equippedStatModOld to set.
     * @return This builder for chaining.
     */
    public Builder setEquippedStatModOld(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEquippedStatModOldIsMutable();
      equippedStatModOld_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @param value The equippedStatModOld to add.
     * @return This builder for chaining.
     */
    public Builder addEquippedStatModOld(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEquippedStatModOldIsMutable();
      equippedStatModOld_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @param values The equippedStatModOld to add.
     * @return This builder for chaining.
     */
    public Builder addAllEquippedStatModOld(
        Iterable<String> values) {
      ensureEquippedStatModOldIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, equippedStatModOld_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearEquippedStatModOld() {
      equippedStatModOld_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipped_stat_mod_old = 20;</code>
     * @param value The bytes of the equippedStatModOld to add.
     * @return This builder for chaining.
     */
    public Builder addEquippedStatModOldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEquippedStatModOldIsMutable();
      equippedStatModOld_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<StatMod> equippedStatMod_ =
      java.util.Collections.emptyList();
    private void ensureEquippedStatModIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        equippedStatMod_ = new java.util.ArrayList<StatMod>(equippedStatMod_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        StatMod, StatMod.Builder, StatModOrBuilder> equippedStatModBuilder_;

    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public java.util.List<StatMod> getEquippedStatModList() {
      if (equippedStatModBuilder_ == null) {
        return java.util.Collections.unmodifiableList(equippedStatMod_);
      } else {
        return equippedStatModBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public int getEquippedStatModCount() {
      if (equippedStatModBuilder_ == null) {
        return equippedStatMod_.size();
      } else {
        return equippedStatModBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public StatMod getEquippedStatMod(int index) {
      if (equippedStatModBuilder_ == null) {
        return equippedStatMod_.get(index);
      } else {
        return equippedStatModBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder setEquippedStatMod(
        int index, StatMod value) {
      if (equippedStatModBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquippedStatModIsMutable();
        equippedStatMod_.set(index, value);
        onChanged();
      } else {
        equippedStatModBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder setEquippedStatMod(
        int index, StatMod.Builder builderForValue) {
      if (equippedStatModBuilder_ == null) {
        ensureEquippedStatModIsMutable();
        equippedStatMod_.set(index, builderForValue.build());
        onChanged();
      } else {
        equippedStatModBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder addEquippedStatMod(StatMod value) {
      if (equippedStatModBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquippedStatModIsMutable();
        equippedStatMod_.add(value);
        onChanged();
      } else {
        equippedStatModBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder addEquippedStatMod(
        int index, StatMod value) {
      if (equippedStatModBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEquippedStatModIsMutable();
        equippedStatMod_.add(index, value);
        onChanged();
      } else {
        equippedStatModBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder addEquippedStatMod(
        StatMod.Builder builderForValue) {
      if (equippedStatModBuilder_ == null) {
        ensureEquippedStatModIsMutable();
        equippedStatMod_.add(builderForValue.build());
        onChanged();
      } else {
        equippedStatModBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder addEquippedStatMod(
        int index, StatMod.Builder builderForValue) {
      if (equippedStatModBuilder_ == null) {
        ensureEquippedStatModIsMutable();
        equippedStatMod_.add(index, builderForValue.build());
        onChanged();
      } else {
        equippedStatModBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder addAllEquippedStatMod(
        Iterable<? extends StatMod> values) {
      if (equippedStatModBuilder_ == null) {
        ensureEquippedStatModIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, equippedStatMod_);
        onChanged();
      } else {
        equippedStatModBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder clearEquippedStatMod() {
      if (equippedStatModBuilder_ == null) {
        equippedStatMod_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        equippedStatModBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public Builder removeEquippedStatMod(int index) {
      if (equippedStatModBuilder_ == null) {
        ensureEquippedStatModIsMutable();
        equippedStatMod_.remove(index);
        onChanged();
      } else {
        equippedStatModBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public StatMod.Builder getEquippedStatModBuilder(
        int index) {
      return getEquippedStatModFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public StatModOrBuilder getEquippedStatModOrBuilder(
        int index) {
      if (equippedStatModBuilder_ == null) {
        return equippedStatMod_.get(index);  } else {
        return equippedStatModBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public java.util.List<? extends StatModOrBuilder>
         getEquippedStatModOrBuilderList() {
      if (equippedStatModBuilder_ != null) {
        return equippedStatModBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(equippedStatMod_);
      }
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public StatMod.Builder addEquippedStatModBuilder() {
      return getEquippedStatModFieldBuilder().addBuilder(
          StatMod.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public StatMod.Builder addEquippedStatModBuilder(
        int index) {
      return getEquippedStatModFieldBuilder().addBuilder(
          index, StatMod.getDefaultInstance());
    }
    /**
     * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
     */
    public java.util.List<StatMod.Builder>
         getEquippedStatModBuilderList() {
      return getEquippedStatModFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        StatMod, StatMod.Builder, StatModOrBuilder>
        getEquippedStatModFieldBuilder() {
      if (equippedStatModBuilder_ == null) {
        equippedStatModBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            StatMod, StatMod.Builder, StatModOrBuilder>(
                equippedStatMod_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        equippedStatMod_ = null;
      }
      return equippedStatModBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:serenno.protos.playerProfileResponse.Unit)
  }

  // @@protoc_insertion_point(class_scope:serenno.protos.playerProfileResponse.Unit)
  private static final Unit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Unit();
  }

  public static Unit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Unit>
      PARSER = new com.google.protobuf.AbstractParser<Unit>() {
    @Override
    public Unit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Unit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Unit> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Unit> getParserForType() {
    return PARSER;
  }

  @Override
  public Unit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

