// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerProfileResponse.proto

package serenno.protos.playerProfileResponse;

public interface UnitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.playerProfileResponse.Unit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string definition_id = 2;</code>
   * @return The definitionId.
   */
  String getDefinitionId();
  /**
   * <code>string definition_id = 2;</code>
   * @return The bytes for definitionId.
   */
  com.google.protobuf.ByteString
      getDefinitionIdBytes();

  /**
   * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
   * @return The enum numeric value on the wire for currentRarity.
   */
  int getCurrentRarityValue();
  /**
   * <code>.serenno.protos.playerProfileResponse.Rarity current_rarity = 8;</code>
   * @return The currentRarity.
   */
  Rarity getCurrentRarity();

  /**
   * <code>int32 current_level = 9;</code>
   * @return The currentLevel.
   */
  int getCurrentLevel();

  /**
   * <code>int32 current_xp = 10;</code>
   * @return The currentXp.
   */
  int getCurrentXp();

  /**
   * <code>string promotion_recipe_reference = 12;</code>
   * @return The promotionRecipeReference.
   */
  String getPromotionRecipeReference();
  /**
   * <code>string promotion_recipe_reference = 12;</code>
   * @return The bytes for promotionRecipeReference.
   */
  com.google.protobuf.ByteString
      getPromotionRecipeReferenceBytes();

  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  java.util.List<Skill>
      getSkillList();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  Skill getSkill(int index);
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  int getSkillCount();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  java.util.List<? extends SkillOrBuilder>
      getSkillOrBuilderList();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.Skill skill = 16;</code>
   */
  SkillOrBuilder getSkillOrBuilder(
      int index);

  /**
   * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
   * @return Whether the unitStat field is set.
   */
  boolean hasUnitStat();
  /**
   * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
   * @return The unitStat.
   */
  StatDef getUnitStat();
  /**
   * <code>.serenno.protos.playerProfileResponse.StatDef unit_stat = 17;</code>
   */
  StatDefOrBuilder getUnitStatOrBuilder();

  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  java.util.List<EquipmentSlot>
      getEquipmentList();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  EquipmentSlot getEquipment(int index);
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  int getEquipmentCount();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  java.util.List<? extends EquipmentSlotOrBuilder>
      getEquipmentOrBuilderList();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.EquipmentSlot equipment = 18;</code>
   */
  EquipmentSlotOrBuilder getEquipmentOrBuilder(
      int index);

  /**
   * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
   * @return The enum numeric value on the wire for currentTier.
   */
  int getCurrentTierValue();
  /**
   * <code>.serenno.protos.playerProfileResponse.UnitTier current_tier = 19;</code>
   * @return The currentTier.
   */
  UnitTier getCurrentTier();

  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @return A list containing the equippedStatModOld.
   */
  java.util.List<String>
      getEquippedStatModOldList();
  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @return The count of equippedStatModOld.
   */
  int getEquippedStatModOldCount();
  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @param index The index of the element to return.
   * @return The equippedStatModOld at the given index.
   */
  String getEquippedStatModOld(int index);
  /**
   * <code>repeated string equipped_stat_mod_old = 20;</code>
   * @param index The index of the value to return.
   * @return The bytes of the equippedStatModOld at the given index.
   */
  com.google.protobuf.ByteString
      getEquippedStatModOldBytes(int index);

  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  java.util.List<StatMod>
      getEquippedStatModList();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  StatMod getEquippedStatMod(int index);
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  int getEquippedStatModCount();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  java.util.List<? extends StatModOrBuilder>
      getEquippedStatModOrBuilderList();
  /**
   * <code>repeated .serenno.protos.playerProfileResponse.StatMod equipped_stat_mod = 21;</code>
   */
  StatModOrBuilder getEquippedStatModOrBuilder(
      int index);
}
