// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthGuestRequest.proto

package serenno.protos.authGuestRequest;

public interface AuthGuestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.authGuestRequest.AuthGuestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   * @return The uid.
   */
  String getUid();
  /**
   * <code>string uid = 1;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string device_platform = 2;</code>
   * @return The devicePlatform.
   */
  String getDevicePlatform();
  /**
   * <code>string device_platform = 2;</code>
   * @return The bytes for devicePlatform.
   */
  com.google.protobuf.ByteString
      getDevicePlatformBytes();

  /**
   * <code>string language = 3;</code>
   * @return The language.
   */
  String getLanguage();
  /**
   * <code>string language = 3;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string player_name = 4;</code>
   * @return The playerName.
   */
  String getPlayerName();
  /**
   * <code>string player_name = 4;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <code>string bundle_id = 5;</code>
   * @return The bundleId.
   */
  String getBundleId();
  /**
   * <code>string bundle_id = 5;</code>
   * @return The bytes for bundleId.
   */
  com.google.protobuf.ByteString
      getBundleIdBytes();

  /**
   * <code>string region = 6;</code>
   * @return The region.
   */
  String getRegion();
  /**
   * <code>string region = 6;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <code>sint32 local_time_zone_offset_minutes = 7;</code>
   * @return The localTimeZoneOffsetMinutes.
   */
  int getLocalTimeZoneOffsetMinutes();

  /**
   * <code>.serenno.protos.authGuestRequest.SessionStartContext session_start_context = 8;</code>
   * @return The enum numeric value on the wire for sessionStartContext.
   */
  int getSessionStartContextValue();
  /**
   * <code>.serenno.protos.authGuestRequest.SessionStartContext session_start_context = 8;</code>
   * @return The sessionStartContext.
   */
  SessionStartContext getSessionStartContext();

  /**
   * <code>.serenno.protos.authGuestRequest.DevicePreferences device_preferences = 9;</code>
   * @return Whether the devicePreferences field is set.
   */
  boolean hasDevicePreferences();
  /**
   * <code>.serenno.protos.authGuestRequest.DevicePreferences device_preferences = 9;</code>
   * @return The devicePreferences.
   */
  DevicePreferences getDevicePreferences();
  /**
   * <code>.serenno.protos.authGuestRequest.DevicePreferences device_preferences = 9;</code>
   */
  DevicePreferencesOrBuilder getDevicePreferencesOrBuilder();
}
