// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthGuestRequest.proto

package serenno.protos.authGuestRequest;

public interface DevicePreferencesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.authGuestRequest.DevicePreferences)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool pushnotes_allowed = 1;</code>
   * @return The pushnotesAllowed.
   */
  boolean getPushnotesAllowed();

  /**
   * <code>bool music_setting = 2;</code>
   * @return The musicSetting.
   */
  boolean getMusicSetting();

  /**
   * <code>bool sfx_setting = 3;</code>
   * @return The sfxSetting.
   */
  boolean getSfxSetting();

  /**
   * <code>string network_connection = 4;</code>
   * @return The networkConnection.
   */
  String getNetworkConnection();
  /**
   * <code>string network_connection = 4;</code>
   * @return The bytes for networkConnection.
   */
  com.google.protobuf.ByteString
      getNetworkConnectionBytes();
}
