// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthGuestRequest.proto

package serenno.protos.authGuestRequest;

/**
 * Protobuf enum {@code serenno.protos.authGuestRequest.SessionStartContext}
 */
public enum SessionStartContext
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PUSHNOTE = 0;</code>
   */
  PUSHNOTE(0),
  /**
   * <code>NORMALAPPSTART = 1;</code>
   */
  NORMALAPPSTART(1),
  /**
   * <code>RESUME = 2;</code>
   */
  RESUME(2),
  /**
   * <code>RESTART = 3;</code>
   */
  RESTART(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PUSHNOTE = 0;</code>
   */
  public static final int PUSHNOTE_VALUE = 0;
  /**
   * <code>NORMALAPPSTART = 1;</code>
   */
  public static final int NORMALAPPSTART_VALUE = 1;
  /**
   * <code>RESUME = 2;</code>
   */
  public static final int RESUME_VALUE = 2;
  /**
   * <code>RESTART = 3;</code>
   */
  public static final int RESTART_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static SessionStartContext valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SessionStartContext forNumber(int value) {
    switch (value) {
      case 0: return PUSHNOTE;
      case 1: return NORMALAPPSTART;
      case 2: return RESUME;
      case 3: return RESTART;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SessionStartContext>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SessionStartContext> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SessionStartContext>() {
          public SessionStartContext findValueByNumber(int number) {
            return SessionStartContext.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return AuthGuestRequestOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final SessionStartContext[] VALUES = values();

  public static SessionStartContext valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SessionStartContext(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:serenno.protos.authGuestRequest.SessionStartContext)
}

