// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlimPlayerArenaProfileResponse.proto

package serenno.protos.slimPlayerArenaProfileResponse;

/**
 * Protobuf enum {@code serenno.protos.slimPlayerArenaProfileResponse.SlimPlayerArenaType}
 */
public enum SlimPlayerArenaType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PlayerArena_None = 0;</code>
   */
  PlayerArena_None(0),
  /**
   * <code>SquadArena = 1;</code>
   */
  SquadArena(1),
  /**
   * <code>FleetArena = 2;</code>
   */
  FleetArena(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PlayerArena_None = 0;</code>
   */
  public static final int PlayerArena_None_VALUE = 0;
  /**
   * <code>SquadArena = 1;</code>
   */
  public static final int SquadArena_VALUE = 1;
  /**
   * <code>FleetArena = 2;</code>
   */
  public static final int FleetArena_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static SlimPlayerArenaType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SlimPlayerArenaType forNumber(int value) {
    switch (value) {
      case 0: return PlayerArena_None;
      case 1: return SquadArena;
      case 2: return FleetArena;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SlimPlayerArenaType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SlimPlayerArenaType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SlimPlayerArenaType>() {
          public SlimPlayerArenaType findValueByNumber(int number) {
            return SlimPlayerArenaType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return SlimPlayerArenaProfileResponseOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final SlimPlayerArenaType[] VALUES = values();

  public static SlimPlayerArenaType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SlimPlayerArenaType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:serenno.protos.slimPlayerArenaProfileResponse.SlimPlayerArenaType)
}

