// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlimPlayerArenaProfileResponse.proto

package serenno.protos.slimPlayerArenaProfileResponse;

public interface SlimPlayerArenaStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.slimPlayerArenaProfileResponse.SlimPlayerArenaStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.serenno.protos.slimPlayerArenaProfileResponse.SlimPlayerArenaType arena_type = 1;</code>
   * @return The enum numeric value on the wire for arenaType.
   */
  int getArenaTypeValue();
  /**
   * <code>.serenno.protos.slimPlayerArenaProfileResponse.SlimPlayerArenaType arena_type = 1;</code>
   * @return The arenaType.
   */
  SlimPlayerArenaType getArenaType();

  /**
   * <code>int32 place = 2;</code>
   * @return The place.
   */
  int getPlace();

  /**
   * <code>.serenno.protos.slimPlayerArenaProfileResponse.SlimArenaTeam arenaTeam = 3;</code>
   * @return Whether the arenaTeam field is set.
   */
  boolean hasArenaTeam();
  /**
   * <code>.serenno.protos.slimPlayerArenaProfileResponse.SlimArenaTeam arenaTeam = 3;</code>
   * @return The arenaTeam.
   */
  SlimArenaTeam getArenaTeam();
  /**
   * <code>.serenno.protos.slimPlayerArenaProfileResponse.SlimArenaTeam arenaTeam = 3;</code>
   */
  SlimArenaTeamOrBuilder getArenaTeamOrBuilder();
}
