// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlimPlayerArenaProfileResponse.proto

package serenno.protos.slimPlayerArenaProfileResponse;

public interface SlimArenaTeamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serenno.protos.slimPlayerArenaProfileResponse.SlimArenaTeam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .serenno.protos.slimPlayerArenaProfileResponse.SlimArenaUnit arenaUnit = 1;</code>
   */
  java.util.List<SlimArenaUnit>
      getArenaUnitList();
  /**
   * <code>repeated .serenno.protos.slimPlayerArenaProfileResponse.SlimArenaUnit arenaUnit = 1;</code>
   */
  SlimArenaUnit getArenaUnit(int index);
  /**
   * <code>repeated .serenno.protos.slimPlayerArenaProfileResponse.SlimArenaUnit arenaUnit = 1;</code>
   */
  int getArenaUnitCount();
  /**
   * <code>repeated .serenno.protos.slimPlayerArenaProfileResponse.SlimArenaUnit arenaUnit = 1;</code>
   */
  java.util.List<? extends SlimArenaUnitOrBuilder>
      getArenaUnitOrBuilderList();
  /**
   * <code>repeated .serenno.protos.slimPlayerArenaProfileResponse.SlimArenaUnit arenaUnit = 1;</code>
   */
  SlimArenaUnitOrBuilder getArenaUnitOrBuilder(
      int index);
}
