// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SlimPlayerArenaProfileResponse.proto

package serenno.protos.slimPlayerArenaProfileResponse;

public final class SlimPlayerArenaProfileResponseOuterClass {
  private SlimPlayerArenaProfileResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaTeam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaTeam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaUnit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaUnit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$SlimPlayerArenaProfileResponse.proto\022-" +
      "serenno.protos.slimPlayerArenaProfileRes" +
      "ponse\"\312\001\n\036SlimPlayerArenaProfileResponse" +
      "\022\014\n\004name\030\001 \001(\t\022\r\n\005level\030\002 \001(\005\022\020\n\010allyCod" +
      "e\030\003 \001(\003\022\020\n\010playerId\030\004 \001(\t\022T\n\006arenas\030\005 \003(" +
      "\0132D.serenno.protos.slimPlayerArenaProfil" +
      "eResponse.SlimPlayerArenaStatus\022\021\n\tpvpOf" +
      "fset\030\006 \001(\021\"\317\001\n\025SlimPlayerArenaStatus\022V\n\n" +
      "arena_type\030\001 \001(\0162B.serenno.protos.slimPl" +
      "ayerArenaProfileResponse.SlimPlayerArena" +
      "Type\022\r\n\005place\030\002 \001(\005\022O\n\tarenaTeam\030\003 \001(\0132<" +
      ".serenno.protos.slimPlayerArenaProfileRe" +
      "sponse.SlimArenaTeam\"`\n\rSlimArenaTeam\022O\n" +
      "\tarenaUnit\030\001 \003(\0132<.serenno.protos.slimPl" +
      "ayerArenaProfileResponse.SlimArenaUnit\"\210" +
      "\001\n\rSlimArenaUnit\022\n\n\002id\030\001 \001(\005\022\r\n\005defId\030\002 " +
      "\001(\t\022\r\n\005index\030\003 \001(\005\022M\n\010slotType\030\014 \001(\0162;.s" +
      "erenno.protos.slimPlayerArenaProfileResp" +
      "onse.SlimSlotType*K\n\023SlimPlayerArenaType" +
      "\022\024\n\020PlayerArena_None\020\000\022\016\n\nSquadArena\020\001\022\016" +
      "\n\nFleetArena\020\002*Z\n\014SlimSlotType\022\020\n\014SlotTy" +
      "peNONE\020\000\022\010\n\004UNIT\020\001\022\n\n\006LEADER\020\002\022\020\n\014CAPITA" +
      "L_SHIP\020\003\022\020\n\014REINFORCMENT\020\005B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaProfileResponse_descriptor,
        new String[] { "Name", "Level", "AllyCode", "PlayerId", "Arenas", "PvpOffset", });
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimPlayerArenaStatus_descriptor,
        new String[] { "ArenaType", "Place", "ArenaTeam", });
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaTeam_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaTeam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaTeam_descriptor,
        new String[] { "ArenaUnit", });
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaUnit_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaUnit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serenno_protos_slimPlayerArenaProfileResponse_SlimArenaUnit_descriptor,
        new String[] { "Id", "DefId", "Index", "SlotType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
