// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestEnvelope.proto

package serenno.protos.requestEnvelope;

/**
 * Protobuf enum {@code serenno.protos.requestEnvelope.AcceptEncoding}
 */
public enum AcceptEncoding
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DEFAULTACCEPTENCODING = 0;</code>
   */
  DEFAULTACCEPTENCODING(0),
  /**
   * <code>GZIPACCEPTENCODING = 1;</code>
   */
  GZIPACCEPTENCODING(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DEFAULTACCEPTENCODING = 0;</code>
   */
  public static final int DEFAULTACCEPTENCODING_VALUE = 0;
  /**
   * <code>GZIPACCEPTENCODING = 1;</code>
   */
  public static final int GZIPACCEPTENCODING_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static AcceptEncoding valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AcceptEncoding forNumber(int value) {
    switch (value) {
      case 0: return DEFAULTACCEPTENCODING;
      case 1: return GZIPACCEPTENCODING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AcceptEncoding>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AcceptEncoding> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AcceptEncoding>() {
          public AcceptEncoding findValueByNumber(int number) {
            return AcceptEncoding.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return RequestEnvelopeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final AcceptEncoding[] VALUES = values();

  public static AcceptEncoding valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AcceptEncoding(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:serenno.protos.requestEnvelope.AcceptEncoding)
}

